### ISSUE TITLE
缺少对个别指令的支持

### ISSUE THREAD

**Issue by daxiaraoming** [hadix-lin/ideavim_extension#10]
发现不支持的指令有o,O,cw,C,S

**Comment by hadix-lin** [comment]
是说开启这个`:set keep-english-in-normal-and-restore-in-insert`之后,这些指令不能将输入法从英文切回原来的输入法吗?

**Comment by hadix-lin** [comment]
ideavim插件,对CommandEvent.getCommandName方法的返回值做了变更,这几个指令的返回值都是Typing,看了一下代码只能通过反射做侵入式的识别,才能处理这个问题.

考虑对性能和复杂度的影响,需要衡量一下这样处理的价值.

**Comment by daxiaraoming** [comment]
暂时先保持关注吧,目前还是我自己的解决方案比较好用(搜狗输入法设置右shift切换中英,karabiner改键盘左下角的键为右shift).

**Comment by hadix-lin** [comment]
搜狗应该是没开放api的,鼠须管api不熟悉.做不到利用输入法的中英切换能力.

另外你的方案实际上是手动执行切换的.

:set keep-english-in-normal-and-restore-in-insert  这个功能在编码时的实际意义并不大.
因为回到插入模式时,基本都是回到正常编码状态一般使用英文进行编码,所以还原到中文作用不大.

除非在编程时写大篇幅的中文注释时,才有意义.
