### ISSUE TITLE
1.6.5版本中文输入法输入后，切回普通模式执行.重复命令，输入法会变成中文

### ISSUE THREAD

**Issue by sxy9699** [hadix-lin/ideavim_extension#100]
版本信息：
IntelliJ IDEA 2022.2 (Ultimate Edition)
ideavim 1.11.1
ideavimextension 1.6.5
输入法用的是win10系统自带的微软拼音
.ideavimrc中设置了
set keep-english-in-normal-and-restore-in-insert 
let context_aware=0

**Comment by hadix-lin** [comment]
我没能复线这个问题，可以录屏吗？

**Comment by hadix-lin** [comment]
长时间没有收到回复
