### ISSUE TITLE
如何获取输入法的input_source_id呢？

### ISSUE THREAD

**Issue by zifeiYv** [hadix-lin/ideavim_extension#101]
如题。

我想要通过设置`keep_input_source_in_insert`来使得输入法在进入插入模式时变成搜狗输入法，该如何获取输入法的input source id呢？

操作系统：macOS

**Comment by hadix-lin** [comment]
可以使用[im-select](https://github.com/daipeihust/im-select)来获取当前使用的输入法id

**Comment by zifeiYv** [comment]
有效，可关。
