### ISSUE TITLE
无法正常恢复中文输入法

### ISSUE THREAD

**Issue by HUMDRFGRY** [hadix-lin/ideavim_extension#103]
https://user-images.githubusercontent.com/40079086/193302028-711bb8d3-769e-431b-b41a-3327be17af88.mp4

IDEA版本：IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Windwos版本：Windwos11 22H2
中文输入法：搜狗五笔
<img width="259" alt="image" src="https://user-images.githubusercontent.com/40079086/193300923-6330a0b9-b772-4827-a44c-251da0fd7213.png">

上述版本只有在中文句子中间才能恢复之前的中文输入法，在中文句子末尾和中文句子开头，或者从中文行换行后都没法正常恢复原来的中文输入法。

**Comment by hadix-lin** [comment]
从1.6开始增加了一个根据上下文判断是否恢复输入法的配置，默认是开启的。开启时之后光标两侧的字符都是非英文时才会恢复输入法。

可以通过在`.ideavimrc`中通过`let context_aware=0`关闭这个功能
