### ISSUE TITLE
idea 2022.3无法正常使用

### ISSUE THREAD

**Issue by jackytang** [hadix-lin/ideavim_extension#104]
正在使用idea 2022.3 eap版本, 今天更新了ideavim 2.0在插入模式下按⎋切换到normal模式无法自动切换到英文输入法模式

**Comment by hadix-lin** [comment]
你好积极啊，开始用eap版本了……抽空我看看

**Comment by jackytang** [comment]
哈哈, 比较喜欢最新版本的使用, 发现这个插件不能使用, 真是好不习惯, 所以忍不住发了issues

**Comment by jackytang** [comment]
想自己修改以后打包, 但是一直报异常, 折腾了蛮久也没解决, 错误如下
> Task :runIde
2022-11-11 16:39:30,542 [    704]   WARN - #c.i.i.AppStarter - Unable to load JNA library (os=Mac OS X 11.6, jna.boot.library.path=null)
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/darwin-x86-64/libjnidispatch.jnilib) not found in resource path (/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/util.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/app.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/3rd-party-rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/platform-statistics-devkit.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/jps-model.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/stats.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/protobuf.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/external-system-rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/forms_rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/intellij-test-discovery.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/annotations.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/groovy.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/3rd-party-native.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/annotations-java5.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/byte-buddy-agent.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/error-prone-annotations.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/externalProcess-rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/idea_rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/intellij-coverage-agent-1.0.682.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/jsch-agent.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/jsp-base.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/junit.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/junit4.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/kotlin-script-runtime.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/platform-duplicates-analysis.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/platform-objectSerializer-annotations.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/platform-structuralSearch.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/rd.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/tools-testsBootstrap.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/util_rt.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/xml-dom-impl.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/xml-dom.jar:/Users/JackyTang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4c6c05d0c6d7a2ebafa2e6bae5bc75f1fcb48c4c/ideaIC-LATEST-EAP-SNAPSHOT/lib/ant/lib/ant.jar)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1059)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at com.intellij.jna.JnaLoader.load(JnaLoader.java:19)
	at com.intellij.idea.StartupUtil$loadSystemLibsAndLogInfoAndInitMacApp$1$2.invokeSuspend(StartupUtil.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-11 16:39:35,214 [   5376]   WARN - o.j.n.NativeTrustedRootsInternalUtils - Unable to get custom trusted certificates list from the operating system: Could not initialize class com.sun.jna.Native
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native

**Comment by hadix-lin** [comment]
我试了一下不太好调试，我从来没为EAP版本配置过开发环境，暂时没时间研究。

建议还是用正式版本吧，IDEA更新之后，一般为会在2天内跟着跟新。

**Comment by jackytang** [comment]
哦, 好吧, 我已经用hammerspoon实现了同样的功能, 不过是不限于idea

**Comment by jackytang** [comment]
> 这个问题有解了吗？同2022.3版本，因为mac在m1下使用老版本偶尔有黑屏现象，所以无奈升级到最新版。

应该还没解决吧，我已经换解决办法了，karabiner也可以实现，

**Comment by hadix-lin** [comment]
2022.3已经RC2了，很快就会Release了，直接适配正式版。

**Comment by hadix-lin** [comment]
> > 这个问题有解了吗？同2022.3版本，因为mac在m1下使用老版本偶尔有黑屏现象，所以无奈升级到最新版。
> 
> 应该还没解决吧，我已经换解决办法了，karabiner也可以实现，

可以分享一下karabiner的方案吗？

**Comment by jackytang** [comment]
> > > 这个问题有解了吗？同2022.3版本，因为mac在m1下使用老版本偶尔有黑屏现象，所以无奈升级到最新版。
> > 
> > 应该还没解决吧，我已经换解决办法了，karabiner也可以实现，
> 
> 可以分享一下karabiner的方案吗？

可以，其实karabiner社区就有，只是karabiner是除了idea，其他情况按esc也会切换成英文输入法

**Comment by jackytang** [comment]
> 已经回滚到2022.2.4的版本了，这个版本mac os13 的黑屏问题也解决了，了解到了hammerspoon，开启了新世界的大门，原先装了好多小插件，现在直接用这个替换了

是的，功能强大，设置应用的快捷键，网速，窗口管理，我还有个识别到外键键盘自动切换karabiner配置文件，禁用笔记本自带键盘，挺方便的

**Comment by sailor103** [comment]
您好，昨天webstorm 2022.3正式发布了，好像这个插件失效了，后面可以更新一个版本吗。不胜感激。

**Comment by hadix-lin** [comment]
[1.6.6](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.6/IdeaVimExtension-1.6.6.zip)解决该问题
