### ISSUE TITLE
插件不稳定, 随便一试就出问题

### ISSUE THREAD

**Issue by xiexiaobo135** [hadix-lin/ideavim_extension#105]
win10, WebStorm 2022.2.3 中, 
配置的是 set keep-english-in-normal-and-restore-in-insert
随便按ESC 和 i 交替按快些就出现问题, 一会有自动切换输入法, 一会而又没有. 有时等几秒钟再按 i 进入后又出现能切到中文了, 感觉就像是在队列里判断, 结果却有延时一样.  按快了进插入模式就没自动切换功能了, 退出等会再进又有了, 这样的判断逻辑肯定是有问题的.

**Comment by xiexiaobo135** [comment]
还有就是 a, s, i, A, I, o, O 这些进入插入模式的情况都不一致, 一会这个有一会而那个有, 同样的情况按 i 进去能切到中文, 退出来后按别的其它键进入又不行了, 再退出用 i 进, 结果 i 也不行了. 完全𢵵不到头脑.

**Comment by hadix-lin** [comment]
默认情况会开启根据上下文判断是否要切换输入法的特性，如果觉得行为不稳定，可以关掉该功能。
在.ideavimrc中添加如下内容
let context_aware=1

**Comment by 3bluebird** [comment]
@hadix-lin `IntelliJ IDEA 2022.3 (Community Edition)` 不生效，`IntelliJ IDEA 2022.3 (Ultimate)` 却使用正常😂

**Comment by hadix-lin** [comment]
今天更新了个版本 [1.6.6](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.6/IdeaVimExtension-1.6.6.zip)，暂时没有上传到插件仓库，可以手动安装试一下

另外我上一条回复发的配置错误 `let context_aware=0`才是关闭

**Comment by hadix-lin** [comment]
长时间未得到回复
