### ISSUE TITLE
insert模式无法切换回中文输入法

### ISSUE THREAD

**Issue by justou** [hadix-lin/ideavim_extension#107]
系统 Windows 10 Pro 22H2
输入法1：Chinese（Simplified，China）Microsoft Pinyin
输入法2：English（United States）US Keyboard

IdeaVim 1.10.3
IdeaVimExtension 1.6.5
PyCharm CLion中直接搜索的以上两个插件并安装

insert模式下使用微软拼音，ESC后输入法能自动切换为ENG (English（United States）US Keyboard)，但是再进入insert模式还是保持ENG输入法不变

.ideavimrc中增加了以下设置
`set keep-english-in-normal-and-restore-in-insert`
已重启IDE，也通在normal模式下`:set keep-english-in-normal-and-restore-in-insert` 
做个各种尝试，总之就是无法自动切回微软拼音。

**Comment by hadix-lin** [comment]
.ideavimrc中加入let context_aware=0 试一下

或者升级到IdeaVIM2.0，IdeaVimExtension 1.6.6

**Comment by justou** [comment]
> .ideavimrc中加入let context_aware=0 试一下
> 
> 或者升级到IdeaVIM2.0，IdeaVimExtension 1.6.6

let context_aware=0可解， 感谢！
似乎必须要设置这个变量才可以，let context_aware=0或1都可以得到正确的行为，不设置就会出现上面描述的问题。

**Comment by hadix-lin** [comment]
context_aware=1 回到insert模式的时候，如果光标两侧都是非ASCII字符才会恢复输入法
context_aware=0 回到insert模式就恢复输入法
