### ISSUE TITLE
MacOS 1.6.6 版本功能失效

### ISSUE THREAD

**Issue by cbconne** [hadix-lin/ideavim_extension#108]
IdeaVim 2.0.0
IdeaVimExtension 1.6.6
MacOs 13.1 (22C65)
IntelliJ IDEA 2022.3.1 (Ultimate Edition)

安装后功能失效，无法正常切换输入法，回退至 1.6.5 版本后正常

**Comment by yangy577** [comment]
+1
IntelliJ IDEA 2022.3.1 
IdeaVim 2.0.0
IdeaVimExtension 1.6.6
MacOs 13.1 (22C65)

配置文件.ideavimrc 中 let context_aware=1 ,let context_aware=0 均不起作用

安装后功能失效，无法正常切换输入法，回退至 1.6.5 版本后正常

**Comment by SmartRiver** [comment]
IdeaVim 2.0.0
IdeaVimExtension 1.6.6
MacOs 13.1 (22A400)
GoLand 2022.3.1

安装后功能失效，无法正常切换输入法

**Comment by iDvel** [comment]
同以上环境，ABC 和 Rime 之间也无法切换。

**Comment by jackytang** [comment]
额, 原来不是我一个人有这个问题

**Comment by hadix-lin** [comment]
该问题是由于IDEA 2022.3.1修改了NativeLib的加载逻辑。[1.6.7](https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.7)修正该问题，但只支持IDEA 2022.3.1以上用户安装，其他用户不要使用。

**Comment by SmartRiver** [comment]
> 该问题是由于IDEA 2022.3.1修改了NativeLib的加载逻辑。[1.6.7](https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.7)修正该问题，但只支持IDEA 2022.3.1以上用户安装，其他用户不要使用。

GoLand 2022.3.1 升级到 1.6.7 还是不行，请问是只修复了 IDEA2022.3.1嘛

**Comment by hadix-lin** [comment]
> > 该问题是由于IDEA 2022.3.1修改了NativeLib的加载逻辑。[1.6.7](https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.7)修正该问题，但只支持IDEA 2022.3.1以上用户安装，其他用户不要使用。
> 
> GoLand 2022.3.1 升级到 1.6.7 还是不行，请问是只修复了 IDEA2022.3.1嘛

理论上都是可以的，但是我只使用IU无法对其他的Jetbrains产品做测试
