### ISSUE TITLE
MacOS系统必须保留“美国”键盘

### ISSUE THREAD

**Issue by zhushijun** [hadix-lin/ideavim_extension#11]
我删除了“美国”键盘选项保留了ABC和搜狗，导致插件不能正常使用。
添加回“美国”键盘后使用恢复正常
建议增加多种英文键盘支持

**Comment by hadix-lin** [comment]
不知道从哪个版本开始macOS的默认英文输入法变成了ABC,下次更新会支持这个键盘.

**Comment by hadix-lin** [comment]
1.1.4版本支持了ABC键盘.
