### ISSUE TITLE
能否在vim 的 o, shift + o 操作时也生效？

### ISSUE THREAD

**Issue by cynricshu** [hadix-lin/ideavim_extension#110]
在 vim 中，i 是在当前光标处切换 insert mode，o 是换行后进入 insert mode，shift + o 是往上换行后进入 insert mode。
在编程时这三种用法都挺常见的。

**Comment by hadix-lin** [comment]
程序只判断是否进入插入模式，并不区分是什么指令进入插入模式，所以理论上所有进入插入模式的指令都会导致“恢复输入法”功能生效。

如果没生效，可以尝试升级到最新版本，并关闭上下文识别功能。`let context_aware=1`
