### ISSUE TITLE
【webstorm】请问能否兼容下WebStorm 2022.3.1 版本？

### ISSUE THREAD

**Issue by sailor103** [hadix-lin/ideavim_extension#111]
Plugin 'IdeaVimExtension' (version '1.6.7') is not compatible with the current version of the IDE, because it requires build 223.8214.52 or newer but the current build is WS-223.8214.51

下载了1.6.7，本地安装报错啦，麻烦问下是什么问题啊。

**Comment by sailor103** [comment]
![image](https://user-images.githubusercontent.com/2821687/209766712-8a5bb466-208c-44d7-bc59-b6e40800526a.png)
如上图

**Comment by sailor103** [comment]
找到一个临时的解决方案，将**IdeaVimExtension-1.6.7.zip**下载下来，解压，然后使用Vim编辑`ideavim_extension-1.6.7.jar`将`META-INF/plugin.xml`中的`223.8214.52`改成`223.8214.51`，并保存，使用WebStorm从本地安装，就可以了。

**Comment by hadix-lin** [comment]
最近两次IDEA的更新，对Native Lib加载做了两次变更，所以才会有这个兼容问题。
由于我只使用IU，无法对其他的进行面面俱到的测试，难免会有遗漏。

**Comment by hadix-lin** [comment]
https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.8/IdeaVimExtension-1.6.8.zip 

下载这个版本试试看

**Comment by sailor103** [comment]
> https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.8/IdeaVimExtension-1.6.8.zip
> 
> 下载这个版本试试看

谢谢，已成功
