### ISSUE TITLE
更新到1.6.10后有问题：在linux、普通模式下，激活命令模式，会被切换到中文输入法

### ISSUE THREAD

**Issue by XiaoLey** [hadix-lin/ideavim_extension#115]
系统：Manjaro

输入法：Fcitx5 5.0.23-1

配置项：
```yaml
set keep-english-in-normal
```

场景复现：打开CLion，输入法自动转为英文，此时为普通模式；按 `Shift + ;` 进入命令模式，输入法自动切换到了拼音输入法，按下 `Esc`，输入法又自动切换回英文输入法。正常情况下应该不会进行切换。

目前解决办法：回退版本到1.6.9

**Comment by hadix-lin** [comment]
现在的状态保存机制，在linux确实可能存在混乱，我会尽快修正该问题。

**Comment by hadix-lin** [comment]
> 系统：Manjaro
> 
> 输入法：Fcitx5 5.0.23-1
> 
> 配置项：
> 
> ```yaml
> set keep-english-in-normal
> ```
> 
> 场景复现：打开CLion，输入法自动转为英文，此时为普通模式；按 `Shift + ;` 进入命令模式，输入法自动切换到了拼音输入法，按下 `Esc`，输入法又自动切换回英文输入法。正常情况下应该不会进行切换。
> 
> 目前解决办法：回退版本到1.6.9

你的意思是说，最后一次按下`Esc`之后没有切换到Normal模式，但是却执行了切换到英文输入法到操作？

**Comment by hadix-lin** [comment]
> 系统：Manjaro
> 
> 输入法：Fcitx5 5.0.23-1
> 
> 配置项：
> 
> ```yaml
> set keep-english-in-normal
> ```
> 
> 场景复现：打开CLion，输入法自动转为英文，此时为普通模式；按 `Shift + ;` 进入命令模式，输入法自动切换到了拼音输入法，按下 `Esc`，输入法又自动切换回英文输入法。正常情况下应该不会进行切换。
> 
> 目前解决办法：回退版本到1.6.9

你的意思是，进入命令模式的时候不应该切换输入法，对吧？

**Comment by XiaoLey** [comment]
确实啊，亦或者说，在命令模式应该默认为英文输入法，毕竟在命令模式很多情况下都是以输入英文为主的

**Comment by XiaoLey** [comment]
而且通常进入命令模式都是从普通模式进入的，而普通模式通常用的是英文输入法，既然这样，我感觉进入命令模式时不进行输入法切换应该较为妥当。

**Comment by hadix-lin** [comment]
> 

之前不会有这个问题，只是最近加了识别焦点变更，有一些情况没有考虑清楚。等会儿发个版本回退到之前的行为逻辑

**Comment by XiaoLey** [comment]
> 我认为是不是模式写错了呢,尝试更换keep-english-in-normal-and-restore-in-insert,我使用一切正常,很丝滑.

你怎么可以这么丝滑……我专门又升级一次使用你说的这个模式，还是有问题。。。我坐等一波作者的更新。

**Comment by gftxdy** [comment]
我遇到了同样的问题

系统：macOS 13.3.1

IDE: IntelliJ IDEA 2023.1

插件版本：1.6.10

配置：
```
set keep-english-in-normal
let keep_input_source_in_normal="com.apple.keylayout.UnicodeHexInput"
```

现象：insert 模式下切换到中文输入法写了注释，esc 回到普通模式，自动切换到了英文输入法，但是如果这时候光标离开编辑器，进入例如 idea 自带的 terminal 或者 idea 某个搜索框，就会切换成中文输入法。

回退到 1.6.9 版本就没有这个问题。

**Comment by hadix-lin** [comment]
已经回退了该行为到1.6.9的模式，请更新到最新版本。
