### ISSUE TITLE
win11系统自带的输入法，在正常模式能自动切换英语模式，但是输入模式不会自动切换，需要用win+空格去切换键盘

### ISSUE THREAD

**Issue by Contentsearch** [hadix-lin/ideavim_extension#116]
在win11系统安装idea2022.2.3和extension插件，并在`.ideavimrc` 配置了自动配置
![image](https://github.com/hadix-lin/ideavim_extension/assets/51782090/2f46d044-8947-4e7d-bac1-602effc366b2)
也安装了美国英语键盘

问题：
  在normal模式能自动切换到美国英语键盘，但是进入插入模式后，不能自动切换搭配中文键盘，需要使用win+空格 去手动切换键盘
为中文拼音，这种情况是正常的吗？是否有自动来回切换之法？ 感觉使用win+空格来切换输入法，比切换中英文状态更麻烦
![image](https://github.com/hadix-lin/ideavim_extension/assets/51782090/415f8489-1240-4b33-b5e3-468f83cd5cc9)

**Comment by hadix-lin** [comment]
正常情况下是可以在回到instert模式的时候自动切换回进入normal模式之前的输入法

只需要设置set keep-english-in-normal-and-restore-in-insert即可
如果输入法切换行为依然不符合预期，在加上let context_aware = 0 这个配置试试

**Comment by c-cheng** [comment]
> 我也遇到同样的问题，并且设置了set keep-english-in-normal-and-restore-in-insert 和 let context_aware = 0 ，仍然无法切换

**Comment by c-cheng** [comment]
2023-06-06更新：
之前无法切换输入法，可能是因为let context_aware = 0了，因为我刚发现如果在中文的地方进入insert模式，它会自动换到中文输入法，如果是在英文的地方进入insert模式，它就不会切换到中文输入法。可能新版本更换了context_aware的处理逻辑？
现在我设置为【set keep-english-in-normal-and-restore-in-insert】和【let context_aware = 1】，不管在任何地方切换insert模式都可以中英文正常切换了，终于舒服多了，以下为我的配置：



" 为IdeaVim插件增加自动切换为英文输入法的功能, idea 需要安装 IdeaVimExtension plugin
"set keep-english-in-normal "开启输入法自动切换功能
set keep-english-in-normal-and-restore-in-insert "回到insert模式时恢复输入法
"set nokeep-english-in-normal-and-restore-in-insert "保留输入法自动切换功能，但是回到insert模式不恢复输入法
"set nokeep-english-in-normal "关闭输入法自动切换功能
let context_aware = 1 "回到insert模式就恢复输入法 
"let context_aware = 0 "回到insert模式的时候，如果光标两侧都是非ASCII字符才会恢复输入法
" 直接指定insert模式和normal模式使用的输入法，输入法的id可以通过im-select项目获取，github地址：https://github.com/daipeihust/im-select
"let keep_input_source_in_insert=2052 "设置insert模式使用到非英文输入法
"let keep_input_source_in_normal=1033 "设置normal模式使用到输入英文到输入法

**Comment by hadix-lin** [comment]
context_aware = 1 的逻辑可能会导致输入法切换的逻辑的可预测性变差，所以默认设置为1了。

**Comment by Contentsearch** [comment]
> 2023-06-06更新： 之前无法切换输入法，可能是因为let context_aware = 0了，因为我刚发现如果在中文的地方进入insert模式，它会自动换到中文输入法，如果是在英文的地方进入insert模式，它就不会切换到中文输入法。可能新版本更换了context_aware的处理逻辑？ 现在我设置为【set keep-english-in-normal-and-restore-in-insert】和【let context_aware = 1】，不管在任何地方切换insert模式都可以中英文正常切换了，终于舒服多了，以下为我的配置：
> 
> " 为IdeaVim插件增加自动切换为英文输入法的功能, idea 需要安装 IdeaVimExtension plugin "set keep-english-in-normal "开启输入法自动切换功能 set keep-english-in-normal-and-restore-in-insert "回到insert模式时恢复输入法 "set nokeep-english-in-normal-and-restore-in-insert "保留输入法自动切换功能，但是回到insert模式不恢复输入法 "set nokeep-english-in-normal "关闭输入法自动切换功能 let context_aware = 1 "回到insert模式就恢复输入法 "let context_aware = 0 "回到insert模式的时候，如果光标两侧都是非ASCII字符才会恢复输入法 " 直接指定insert模式和normal模式使用的输入法，输入法的id可以通过im-select项目获取，github地址：https://github.com/daipeihust/im-select "let keep_input_source_in_insert=2052 "设置insert模式使用到非英文输入法 "let keep_input_source_in_normal=1033 "设置normal模式使用到输入英文到输入法

你使用的是哪个版本的idea和extension插件？

**Comment by Contentsearch** [comment]
> 2023-06-06更新： 之前无法切换输入法，可能是因为let context_aware = 0了，因为我刚发现如果在中文的地方进入insert模式，它会自动换到中文输入法，如果是在英文的地方进入insert模式，它就不会切换到中文输入法。可能新版本更换了context_aware的处理逻辑？ 现在我设置为【set keep-english-in-normal-and-restore-in-insert】和【let context_aware = 1】，不管在任何地方切换insert模式都可以中英文正常切换了，终于舒服多了，以下为我的配置：
> 
> " 为IdeaVim插件增加自动切换为英文输入法的功能, idea 需要安装 IdeaVimExtension plugin "set keep-english-in-normal "开启输入法自动切换功能 set keep-english-in-normal-and-restore-in-insert "回到insert模式时恢复输入法 "set nokeep-english-in-normal-and-restore-in-insert "保留输入法自动切换功能，但是回到insert模式不恢复输入法 "set nokeep-english-in-normal "关闭输入法自动切换功能 let context_aware = 1 "回到insert模式就恢复输入法 "let context_aware = 0 "回到insert模式的时候，如果光标两侧都是非ASCII字符才会恢复输入法 " 直接指定insert模式和normal模式使用的输入法，输入法的id可以通过im-select项目获取，github地址：https://github.com/daipeihust/im-select "let keep_input_source_in_insert=2052 "设置insert模式使用到非英文输入法 "let keep_input_source_in_normal=1033 "设置normal模式使用到输入英文到输入法


我在

**Comment by Contentsearch** [comment]
![image](https://github.com/hadix-lin/ideavim_extension/assets/51782090/87f117db-603f-466f-8cbd-7ef0df45a094)
刚刚又多次测试要删除 `set keep-english-in-normal` 才生效，如上图；
好像每次重启idea后要手动切换一次，后面就可以自动识别了。
