### ISSUE TITLE
插件在Intellij IDEA 2023.2.3下崩溃

### ISSUE THREAD

**Issue by Bryan2333** [hadix-lin/ideavim_extension#118]
RT，插件IDEA 2023.2.3崩溃。

我用的JBR是官方为修复Linux下输入框不跟随光标打了Patch的版本，具体见
https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04#focus=Comments-27-8112829.0-0

[idea.log](https://github.com/hadix-lin/ideavim_extension/files/12911671/idea.log)
这是崩溃时IDEA的日志，相关的报错信息在8131行

**Comment by hadix-lin** [comment]
插件在linux上需要通过
"QT_IM_MODULE"
"GTK_IM_MODULE"

读取这两个环境变量判断当前使用的输入法，这个报错是因为没有设置这两个变量。
一般来说安装了ibus 或者fcitx应该会自动设置这两个变量，你可以试试手动设置这两个系统环境变量。

**Comment by Bryan2333** [comment]
设置了这两个变量后就没再崩溃了。

**Comment by hadix-lin** [comment]
> 设置了这两个变量后就没再崩溃了。

现在使用正常了吗？

**Comment by Bryan2333** [comment]
> > 设置了这两个变量后就没再崩溃了。
> 
> 现在使用正常了吗？

嗯，使用正常了。
