### ISSUE TITLE
Esc 无法切换，ctrl + [ 正常 ！！！

### ISSUE THREAD

**Issue by tille1229** [hadix-lin/ideavim_extension#119]
如题，在 `windows 11 `编辑器：`idea 2023.2.2 `插件版本：`1.6.12` 插入模式中。切换至中文输入法，`Esc ` 回退普通模式后，输入法无法切换。同样的情况下测试 ` ctrl+[ ` 能使用正常。尝试以下方法：
1. ` .ideavimrc` 中添加  `let context_aware=0` ，印象中应该是默认`0`,无效
2. 尝试将 insert 模式中 `Esc` 映射成 `C-[`，依然无效;

盼回复！！

**Comment by hadix-lin** [comment]
我没有windows开发环境，比较难复现您的问题，我想想办法。

**Comment by hadix-lin** [comment]
如果可以的话，是否可以请您帮忙调试一下？clone我的工程，运行调试一下，我告诉你在哪里打断点

**Comment by hadix-lin** [comment]
使用了ideavim-eap导致，ideavim-extension现在的兼容策略是始终跟进ideavim的正式版本，不保证能跟上eap。
