### ISSUE TITLE
IdeaVim升级到2.7.0之后不能自动切换了

### ISSUE THREAD

**Issue by xuelingkang** [hadix-lin/ideavim_extension#121]
环境：
MacOS 14.0
IDEA 2023.2.4
IdeaVim 2.7.0
IdeaVimExtension 1.7.0

当前模式：
set keep-english-in-normal

问题：
在升级IdeaVim之前正常使用，升级之后，从编辑模式切换到命令模式不能自动切换为英文输入法。

**Comment by leodream** [comment]
在Liux环境也遇到相同的问题，但不确定是怎么触发的

KDE 5.27.9
IDEA 2023.1.3 (Community Edition)
IdeaVim 2.7.0
IdeaVimExtension 1.7.0

**Comment by hadix-lin** [comment]
https://github.com/hadix-lin/ideavim_extension/releases/download/v1.7.1/IdeaVimExtension-1.7.1.zip 请下载这个版本安装

**Comment by leodream** [comment]
更新到1.7.1之后可以了，谢谢！只用了“keep-english-in-normal” 没试其他。

**Comment by buptlibo** [comment]
@hadix-lin   我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。
跟1.7.0正好反过来

**Comment by xuelingkang** [comment]
> @hadix-lin 我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。 跟1.7.0正好反过来

我都没升，昨天发现了问题就把IdeaVim降级到2.6.3了，现在作者发的是临时解决方案，等作者发布正式的插件吧

**Comment by hadix-lin** [comment]
> > @hadix-lin 我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。 跟1.7.0正好反过来
> 
> 我都没升，昨天发现了问题就把IdeaVim降级到2.6.3了，现在作者发的是临时解决方案，等作者发布正式的插件吧

确实是临时方案，最近换了新工作，有点儿卷，周末有空再好好看看

**Comment by hadix-lin** [comment]
> @hadix-lin 我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。 跟1.7.0正好反过来

https://github.com/hadix-lin/ideavim_extension/releases/download/v1.7.2/IdeaVimExtension-1.7.2.zip  支持了ctrl+[请试一下

**Comment by buptlibo** [comment]
> > @hadix-lin 我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。 跟1.7.0正好反过来
> 
> https://github.com/hadix-lin/ideavim_extension/releases/download/v1.7.2/IdeaVimExtension-1.7.2.zip 支持了ctrl+[请试一下

👍 可以了，辛苦老哥
看了下代码是把escape和insertexitmode都加上判断了，不过我刚才翻ideavim的youtrack，估计是ideavim这次更新又出问题了
<img width="637" alt="截屏2023-11-10 11 13 57" src="https://github.com/hadix-lin/ideavim_extension/assets/12469651/4eb6bf94-c808-442c-b166-1b3ddca07818">

**Comment by hadix-lin** [comment]
> > > @hadix-lin 我这边升级到1.7.1之后，ESC可以正常切换到英文输入法，但是ctrl+[又不行了。。 跟1.7.0正好反过来
> > 
> > 
> > https://github.com/hadix-lin/ideavim_extension/releases/download/v1.7.2/IdeaVimExtension-1.7.2.zip 支持了ctrl+[请试一下
> 
> 👍 可以用了，老哥辛苦 看了下代码是把escape和insertexitmode都加上判断了，不过我刚才翻ideavim的youtrack，估计是ideavim这次更新又出问题了 <img alt="截屏2023-11-10 11 13 57" width="637" src="https://user-images.githubusercontent.com/12469651/281943075-4eb6bf94-c808-442c-b166-1b3ddca07818.png">

正常来说，escape应该也是触发InsertExitModeAction指令的，但是升级2.7.0之后，变成了Escape指令，所以要单独处理。

**Comment by caijinyc** [comment]
安装升级包之后可以了，感恩作者！

**Comment by hahaleyile** [comment]
我这边还是 esc 不行，但是 Ctrl+[ 可以

**Comment by hahaleyile** [comment]
并且用 i 进入编辑模式时有时候不会切换到中文

**Comment by hadix-lin** [comment]
> 我这边还是 esc 不行，但是 Ctrl+[ 可以

确认插件版本是1.7.3

**Comment by hahaleyile** [comment]
是 1.7.3，设置 let context_aware=0 后确实能解决用 i 进入编辑模式时的问题，但是 Esc 的问题还是解决不了

**Comment by hahaleyile** [comment]
ideavim 版本号为 2.7.3

**Comment by lusuee** [comment]
> 是 1.7.3，设置 let context_aware=0 后确实能解决用 i 进入编辑模式时的问题，但是 Esc 的问题还是解决不了

如果用了中文语言包插件，可以把这个禁用掉试试

**Comment by hahaleyile** [comment]
> > 是 1.7.3，设置 let context_aware=0 后确实能解决用 i 进入编辑模式时的问题，但是 Esc 的问题还是解决不了
> 
> 如果用了中文语言包插件，可以把这个禁用掉试试 @hahaleyile

额，还真是这个问题，谢啦

**Comment by DEAN-Cherry** [comment]
> > 是 1.7.3，设置 let context_aware=0 后确实能解决用 i 进入编辑模式时的问题，但是 Esc 的问题还是解决不了
> 
> 如果用了中文语言包插件，可以把这个禁用掉试试 @hahaleyile

我也遇到了这个问题，`Ideavim 2.7.5` `IdeaVimExtension 1.7.3`，但是在按照你的说法，在 `Chinese (Simplified)Language Pack` 禁用后解决了。
不过这是为什么呢？

**Comment by transtone** [comment]
用 ideavim_extension 就不能用中文语言包 :(

**Comment by gaomengzhou** [comment]
> > > > 是 1.7.3，设置 let context_aware=0 后确实能解决用 i 进入编辑模式时的问题，但是 Esc 的问题还是解决不了
> > > 
> > > 
> > > 如果用了中文语言包插件，可以把这个禁用掉试试 @hahaleyile
> > 
> > 
> > 我也遇到了这个问题，`Ideavim 2.7.5` `IdeaVimExtension 1.7.3`，但是在按照你的说法，在 `Chinese (Simplified)Language Pack` 禁用后解决了。 不过这是为什么呢？ 未来会有修复吗
> > I also encountered this problem, with `Ideavim 2.7.5` and `IdeaVimExtension 1.7.3`. However, it was resolved after I disabled the `Chinese (Simplified) Language Pack` according to your suggestion. But why is this the case? Will there be a fix in the future?
> 
> 我没安装过Chinese (Simplified)Language Pack，抽空安装试试看能不能复现解决问题。

安装中文语言包仅仅只是按esc无效， 用组合键或自定义组合键进入normal模式就没问题。 希望能看看。

**Comment by suiyun39** [comment]
安装中文语言包导致的问题，我在 #123 中修了，在作者 merge 发版之前可以先用我从 fork 上打包的插件。

版本号没有变，应该会在发版后提示更新：

[IdeaVimExtension-1.7.3.zip](https://github.com/hadix-lin/ideavim_extension/files/14202210/IdeaVimExtension-1.7.3.zip)

**Comment by hadix-lin** [comment]
> > 安装中文语言包导致的问题，我在 #123 中修了，在作者 merge 发版之前可以先用我从 fork 上打包的插件。
> > 版本号没有变，应该会在发版后提示更新：
> > [IdeaVimExtension-1.7.3.zip](https://github.com/hadix-lin/ideavim_extension/files/14202210/IdeaVimExtension-1.7.3.zip)
> 
> 超级好用。 谢谢！！！

由于新工作比较忙，并未甲亢住院了一段时间，导致问题没有得到及时处理，今天已经合并了该变更，会尽快发布到插件中心。
