### ISSUE TITLE
[new feature]希望能支持“插入-普通模式”：根据配置自动切换会英文输入法

### ISSUE THREAD

**Issue by cncsl** [hadix-lin/ideavim_extension#125]
1. 在 ideavimrc 中配置了普通模式下自动切换到英文输入法，可以正常使用
```
set keep-english-in-normal
set keep-english-in-normal-and-restore-in-insert
```

2. 而在“插入-普通模式下”，目前依然会保留原始的输入法
https://github.com/hadix-lin/ideavim_extension/assets/32363528/526542e1-10e0-4e75-bd90-46761825f3c6

**Comment by hadix-lin** [comment]
如果想在普通模式进入英文状态了，只保留第一行配置即可
如果想在普通模式进入英文输入法，回到插入模式恢复到原来使用的输入法只保留第二行即可

不需要两行都配置
至于视频里面的内容我并没有看懂，意图是什么？什么是“插入-普通模式下”，我也没有 Google 到 vim 有这个模式。

**Comment by cncsl** [comment]
> 如果想在普通模式进入英文状态了，只保留第一行配置即可 如果想在普通模式进入英文输入法，回到插入模式恢复到原来使用的输入法只保留第二行即可
> 
> 不需要两行都配置 至于视频里面的内容我并没有看懂，意图是什么？什么是“插入-普通模式下”，我也没有 Google 到 vim 有这个模式。

插入-普通模式的效果是 *从插入模式切换到普通模式，输入一条普通模式命令后回到插入模式*，这个译名我是从 《vim实用技巧（第二版）》看到的，详细的可以看vim文档: `h i_CTRL-O`。

需求是插入模式下本来是中文输入法，进入插入-普通模式时根据配置自动切换到英文输入法。现状是进入插入-普通模式时不会自动切换

感谢您开发这个插件🫡

**Comment by hadix-lin** [comment]
现在的实现机制是根据执行切换到普通模式的具体指令来触发切换输入法的操作。你说的场景中切换到普通模式的指令不是固定的，以现在的实现机制是无法支持的。需要时间研究一下根据当前的输入模式来切换输入法，最近换了工作压力比较大，而且身体状况不太好，可能需要比较久的时间，抱歉。

**Comment by hadix-lin** [comment]
[IdeaVimExtension-1.8.0.zip](https://github.com/hadix-lin/ideavim_extension/files/14969409/IdeaVimExtension-1.8.0.zip)

我尝试改了一下，现在可以在 ctrl+O 之后自动切换到英文输入法了，但是执行命令normal 模式命令回到 insert 模式后，无法恢复到中文。我暂时没找到好办法，你看看这个包能否改善你的体验。

**Comment by cncsl** [comment]
谢谢您快速支持，我试试之后提交反馈
