### ISSUE TITLE
keep-english-in-normal-and-restore-in-insert with context_aware=1 for Russian and English works strange

### ISSUE THREAD

**Issue by IntoLighter** [hadix-lin/ideavim_extension#126]
For example, I use this latex code:
```
\clist_set:Nn \g_tasks_clist
{
	Изучение предметной области,
	Выбор технологий для распознавания объектов
}
```

When I switch to insert in the middle of any word, I get language of that word. But when I switch in the end of Russian word, I will get English. If I switch in the beginning of word `Изучение` I will get Russian, but for `предметной` I will get English.

OS: macOS, versions of plugins are latest.

**Comment by hadix-lin** [comment]
context_aware implementation is very simple, just check the current cursor position, if the sub-string from position -1 to position + 1 contains any AsciiPrintable characters, the plugin will keep the English input method, otherwise restore the original input method.

Please check your cursor position to see if it meets the above logic

**Comment by IntoLighter** [comment]
So it's checking adjacent characters? I think, in your logic, it should check only for ascii letters. So when I'm between russian letter and digit, I should get the original input method. And what cursor position it checks - position after applying insert transition or before, which was in normal mode? I think it should consider the second for `o` and `O` actions. Anyway, what is original input method?

**Comment by IntoLighter** [comment]
I also tried to use content_aware=0, and it's also working strange. I expect it to select input method which was selected last in last insertion.

**Comment by hadix-lin** [comment]
> I also tried to use content_aware=0, and it's also working strange. I expect it to select input method which was selected last in last insertion.

When the editor enters insert mode, the plug-in remembers the currently used input method, and then reverts to the remembered input method the next time the editor enters insert mode. 

You can also use let keep_input_source_in_insert=[input source id]` to set the input method used in insert mode
