### ISSUE TITLE
完全用不了

### ISSUE THREAD

**Issue by yebei199** [hadix-lin/ideavim_extension#127]
只有ide第一次下载能够使用, 后续重启ide后就无法使用, 甚至卸载了插件再安装都没有用
ide版本:pycharm2024.1
配置文件是这样的
```
let keep_input_source_in_insert=[1033]
let keep_input_source_in_normal=[1033]
set keep-english-in-normal
```

**Comment by yangxuanx** [comment]
建议使用smart input这个插件，支持ideavim中英切换

**Comment by hadix-lin** [comment]
Windows?你这个变量设置在两种状态下使用的输入法是相同的，试试删掉第一行

**Comment by hadix-lin** [comment]
> 只有ide第一次下载能够使用, 后续重启ide后就无法使用, 甚至卸载了插件再安装都没有用 ide版本:pycharm2024.1 配置文件是这样的
> 
> ```
> let keep_input_source_in_insert=[1033]
> let keep_input_source_in_normal=[1033]
> set keep-english-in-normal
> ```

let keep_input_source_in_normal=1033
set keep-english-in-normal

试试只保留这样的配置，另外 1033 对应的是什么输入法？英文？
