### ISSUE TITLE
能调用外部程序切换 IM 吗？

### ISSUE THREAD

**Issue by haolly** [hadix-lin/ideavim_extension#13]
类似于这个 https://github.com/VSCodeVim/Vim#input-method
我看另一个项目https://github.com/rieonke/idea-auto-switch-im 好像是调用一个 native 的程序，如果把这个 native 的程序换成 im-select，不知道是不是就可以在 windows 下面使用了 ？

**Comment by hadix-lin** [comment]
感谢您提供这个线索，我会尽快抽时间来支持
haolly <notifications@github.com>于2018年11月4日 周日21:54写道：

**Comment by hadix-lin** [comment]
看了im-select的实现代码,茅塞顿开.

JNA-PLATRORM看起来应该是直接可以支持到windows切换输入法的功能的.都不需要调用命令行,也不需要单独写native库.周末试试.

**Comment by haolly** [comment]
哈，感谢，因为公司电脑主要是Windows，所以非常期待这个功能可以用在Windows下面

**Comment by hadix-lin** [comment]
@haolly 问题来了,突然发现我没有windows电脑,如果周末找不到可以用的windows开发环境,估计这个功能得托一阵子了.

**Comment by hadix-lin** [comment]
@haolly 好消息来了,这几天就可以更新提供windows支持了,新版插件已经提交插件仓库进行审核了.

**Comment by rieonke** [comment]
可以参考我的新项目 https://github.com/rieonke/im-manager 目前还在完善，最近有点忙没咋弄。支持macOS/Windows/Linux(ibus/fcitx) 以及 nodejs/python/java 的binding

**Comment by hadix-lin** [comment]
@rieonke windows的我解决了.可以直接通过JNA处理.C代码实在搞不定,请问可以帮我写一个本地库吗?
