### ISSUE TITLE
Windows 下切换输入法有bug

### ISSUE THREAD

**Issue by haolly** [hadix-lin/ideavim_extension#14]
插入模式下输入中文，ESC 进入normal，输入法切换为英文，再次进入插入模式，输入法回到刚才的中文，然后切换成英文输入法，ESC进入normal，输入法切换为英文，**再次进入插入模式，输入法没有回到刚才的英文，而是变成了中文**

**Comment by hadix-lin** [comment]
反馈收到,我会尽快解决这个问题.谢谢.

**Comment by hadix-lin** [comment]
@haolly 版本`1.2.1`解决该问题
