### ISSUE TITLE
[MacOS]使用清歌输入法，界面卡死

### ISSUE THREAD

**Issue by Tanlet** [hadix-lin/ideavim_extension#16]
默认使用自带的输入法时，返回normal状态，正常切换成abc输入法。
但是，insert状态使用清歌输入法，返回normal状态时，就会卡死。

**Comment by hadix-lin** [comment]
@Tanlet 插件版本是什么?

**Comment by Tanlet** [comment]
ideavim = 0.50
ideavim_extension = 1.2.2
是这两个插件版本吧

**Comment by hadix-lin** [comment]
可以帮忙测试一下非清歌的其他输入法吗?

比如搜狗输入法,看看能不能正常切换会英文.

**Comment by hadix-lin** [comment]
我是用搜狗输入法的,切换是没问题的.

**Comment by Tanlet** [comment]
试了下，搜狐输入法是能正常切换的。

**Comment by hadix-lin** [comment]
情况收到,我会尽快尝试重现并分析问题,有新的情况我会在这里进行说明.

**Comment by hadix-lin** [comment]
@Tanlet 您的问题我已经重现了.界面卡住的时候发现线程栈卡在操作系统调用的一个循环里.

从1.2.2版本开始,mac切换输入法的操作系统调改为按照操作系统规范派发到ui主线程执行.解决了系统自带输入发切换崩溃的问题.

推测应该是清歌输入法本身没有遵循操作系统规范导致.我试了1.2.1版本,清歌输入法就没有问题.
如果您不使用系统自带输入法,可以下载1.2.1版本的插件安装使用.

下载地址[https://github.com/hadix-lin/ideavim_extension/releases/download/v1.2.1/IdeaVimExtension-1.2.1.zip](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.2.1/IdeaVimExtension-1.2.1.zip)

**Comment by ShikiSuen** [comment]
清歌输入法开源吗？开源的话，相关可能存在的问题可以尝试自己修。
不然的话，业火输入法也是一个敲五笔的选择：https://github.com/qwertyyb/Fire
