### ISSUE TITLE
该如何修改插件以使其支持programmer dvorak布局

### ISSUE THREAD

**Issue by afezeria** [hadix-lin/ideavim_extension#17]
你好，我是一名programmer dvorak布局的始用者
我始用这个链接提供的布局文件
https://www.kaufmann.no/downloads/winnt/kbddvp-1_2_7-i386.exe
并且我将
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layouts\00000804
下的Layout File的值修改为了kbddvp.dll，以使微软拼音输入法采用programmer dvorak布局
请问我该如何修改插件以支持该键盘布局

**Comment by hadix-lin** [comment]
你是希望可以自行设置回到normal状态时切换的输入法吗?

现在是只能切换到英语-美国键盘.暂时不支持自定义,可以考虑在后续的版本上增加配置功能.

**Comment by hadix-lin** [comment]
@afezeria 可以修改源码io.github.hadixlin.iss.win.WinInputSourceSwitcher中的KEY_LAYOUT_US常量为你想要的dvorak布局输入法.然后自己打包.

常量值可以通过im-select工具查询.
后续会为插件增加相应的配置功能,只是本人工作加班比较多,业务时间有限,无法确定发布时间.

**Comment by the-devil-you-know** [comment]
I use Colemak, this change works for me https://github.com/the-devil-you-know/ideavim_extension/commit/e7d4e2b3874891b712505bda003e7b880713ac5e
