### ISSUE TITLE
偶尔会卡死，用的是搜狗输入法 

### ISSUE THREAD

**Issue by zgqq** [hadix-lin/ideavim_extension#18]
系统 10.14.1

**Comment by hadix-lin** [comment]
能提供具体一点儿的情况吗？方便我复现问题
zgqq <notifications@github.com>于2018年12月9日 周日13:19写道：

**Comment by zgqq** [comment]
@hadix-lin idea几个版本都有问题，应该不是idea的问题，我卸载插件后，就不会卡死了

**Comment by hadix-lin** [comment]
https://github.com/hadix-lin/ideavim_extension/releases/download/v1.2.3/IdeaVimExtension-1.2.3.zip

尝试使用异步操作避免IDE卡顿问题,暂时尚未发布到插件中心.

请先从上面的地址下载并安装新版插件试用,如问题为解决或产生其他问题,请及时反馈.

**Comment by hadix-lin** [comment]
新版本未发现卡死问题
