### ISSUE TITLE
可不可以在normal 模式 一直是 英文 的状态 呢？

### ISSUE THREAD

**Issue by ifnk** [hadix-lin/ideavim_extension#19]
可不可以在normal 模式 一直是 英文 的状态 呢？就算手动  切换 到 中文 ，也会马上 自动 切换 到英文 状态 ，这样就不会按错了。（因为按ctrl+f 搜索 的时候 有时候 会输入 中文 搜索，输入法就是 中文 的了，然后 在normal模式下操作 ，结果发现是中文 状态 ……）

**Comment by hadix-lin** [comment]
这个实现起来有点儿难度,因为期望不明确,大部分用户可能那个时候切换输入法去做别的事情了.再回到编辑器时也不确定是要进行何种输入,所以如果强制英文状态,或许更多时候跟用户的真实诉求相反.要把这个需求点想清楚,才能去做解决方案.

现在有些输入法可以指定在某些应用里面默认英文状态,可以尝试用一下看看是否满足需求,比如搜狗就有这样的功能.

或者在这里把你的想法更多的讨论一下.

**Comment by ifnk** [comment]
额我的意思 是 Norma模式 下……一般 Norma模式 下 是不需要 中文的吧…… insert模式下不影响 ……

**Comment by hadix-lin** [comment]
> 额我的意思 是 Norma模式 下……一般 Norma模式 下 是不需要 中文的吧…… insert模式下不影响 ……

这个可能比较复杂
1. 需要检测焦点回到编辑器的事件
2. 回到编辑器立即检查vi(normal/insert)模式
3. 如果用户没有离开编辑器在normal模式下手动切换了输入法(这种情况为了保持normal下的输入法状态需要在每个输入前检查输入法状态)

前面两种相对容易,第三种情况也就是你所说的,如果每个输入前都都检测,可能会引起性能下降,影响输入体验.

我先尝试一下焦点切换时的处理.

**Comment by ifnk** [comment]
您说的编辑器是指idea pycharm 之类 的么？ 我用的win7 他会 根据 不同的程序 保留 当时 的输入法的状态 的，比如 我用chrome ,我刚好 在用中文 打字 ，我切换 到 idea 里面 ，是 中文 状态 ，我 切换到英文，然后 回到 chrome ,chrome 仍然 是英文 。您可以试试 ，因此 不需要 考虑 焦点回到 编辑器吧？ 只考虑 当前 在vi模式 ，并且是normal 模式 就让输入法强制 是英语 的状态 就行……

**Comment by hadix-lin** [comment]
我明白的你的意思,需要识别一下输入焦点切换的事件来进行控制.我对插件开发也不是很熟悉,得找时间研究一下,你提这个需求点非常有价值,谢谢.

**Comment by hadix-lin** [comment]
@ifnk @xue2han 终于有了一些空闲时间来完成这个需求.暂时没有发布到插件中心,请先下载按装试用.

[下载地址](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.1/ideavim_extension-1.3.1.zip)

**Comment by ifnk** [comment]
> @ifnk @xue2han 终于有了一些空闲时间来完成这个需求.暂时没有发布到插件中心,请先下载按装试用.
> 
> [下载地址](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.1/ideavim_extension-1.3.1.zip)

 谢谢 作者  ，这个很棒 呀 ！ 今天刚刚 在 phpstorm 更新 里 看到 了
