### ISSUE TITLE
win10 下 o/O 失效

### ISSUE THREAD

**Issue by tinyweet** [hadix-lin/ideavim_extension#24]
win10下，上一行和下一行输入输入法不能切换回来。

**Comment by tinyweet** [comment]
版本：
1. idea: 2019.1.1
2. ideavimextension: v1.3.3

**Comment by hadix-lin** [comment]
是使用oO两个指令对吗？

tinyweet <notifications@github.com>于2019年4月23日 周二10:52写道：

**Comment by hadix-lin** [comment]
1.3.4修正
