### ISSUE TITLE
win10无法切回中文

### ISSUE THREAD

**Issue by isensen** [hadix-lin/ideavim_extension#29]
使用的是搜狗五笔, 添加了英语美式键盘 , 正常模式可以切到英语 , 但进入插入模式后,无法切回中文输入法,不知道是设置问题还是什么?

**Comment by hadix-lin** [comment]
默认是不会恢复到中文输入法的
需要使用:set keep-english-in-normal-and-restore-in-insert

这个指令加入.ideavimrc也可以

**Comment by isensen** [comment]
一开始我就加入了这个设置, 是放入了.ideavimrc, 还有别的要求吗?

**Comment by hadix-lin** [comment]
能否提供一下你使用的idea版本，ideavim版本，ideavimextension版本，输入法版本，我将尝试重现该问题

**Comment by hadix-lin** [comment]
问题已修复，请下载[v1.3.7](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.7/ideavim_extension.zip)（暂时还未上传到插件中心）安装使用，详细请看使用说明。

**Comment by isensen** [comment]
OK,我去试试, 谢谢~反馈真快
