### ISSUE TITLE
搜狗输入法/自带拼音输入法均无法切换

### ISSUE THREAD

**Issue by HACK21** [hadix-lin/ideavim_extension#3]
> IdeaVIM v0.48
> IdeaVIMExtension v1.1.2
> MacOS 10.11.6

手动执行和 ~/.ideavimrc 都试了不行诶

**Comment by hadix-lin** [comment]
你的系统输入法里面有开启自带的拼音键盘吗?

**Comment by leohxj** [comment]
Mac OS 10.12.5, 开启了自带的英文和中文输入法，配置无效

**Comment by hadix-lin** [comment]
@leohxj 你有看到我上面发的截图吗?我跟你的操作系统版本是一样的.

**Comment by HACK21** [comment]
@hadix-lin  搞定了，系统默认的是 ABC 的英文输入法，要自己添加美式键盘英文输入。搜狗确实没有提供相关 API 蛋疼了

**Comment by Madoshakalaka** [comment]
确实，在Windows上必须要 English( US )，我之前用的是English (Canada) 的输入法都不行

**Comment by 1538379200** [comment]
但是我的能切换成英文，但是输入的时候不能自动切换回来，使用的是windows11自带的输入法

**Comment by hadix-lin** [comment]
> 但是我的能切换成英文，但是输入的时候不能自动切换回来，使用的是windows11自带的输入法

因为使用IDEA的使用场景多半是写代码，进入插入模式的时候，插件无法确定现在是要输入英文还是中文。

所以现在提供两个配置来自定义这个行为：
首先确保已经启用了，进入插入模式恢复输入法的能力：set keep-english-in-normal-and-restore-in-insert
然后可以通过`let context_aware=1` 令插件根据当前光标所在位置前后的字符判断是否要恢复为中文输入
`let context_aware=0`进入输入法后立即无条件恢复为中文输入
