### ISSUE TITLE
您好，能添加绑定其它退出到普通模式的快捷键吗

### ISSUE THREAD

**Issue by combobo** [hadix-lin/ideavim_extension#30]
实际开发中，由于Esc键位距离较远，开发者可能选择通过ideavim设置中的Exit Insert Mode 或 Exit Visual Mode 所设置的快捷键返回到普通模式，但无法达到自动关闭输入法的效果。。
或者说，从功能实现的角度上讲，能否将关闭输入法的逻辑处理写在触发普通模式之后，而不需要关注是谁触发的，哪个键触发的。目前看来只有Esc键触发的返回普通模式能达到自动关闭输入法的效果~
个人见解：我是设置<Alt+i>退出到普通模式的，比起Esc来讲更方便，只需动动手指就可以达到退出效果，而且 out i 也容易记，而<Ctrl + space>关闭输入法比Esc近一个键位，幅度也相对小很多，目前情况是，要在Esc和<Ctrl+space>二者之间来选择一个关闭输入法的功能的话，对于我来说，我更愿意使用<Ctrl+space>的方式，我相信大部分人也是这样的吧，尤其是笔记本的F1键与Esc的亲密关系，带来时不时的失准点到F1弹出帮助窗口让人烦不胜防~

**Comment by hadix-lin** [comment]
我会考虑一下重现这个状况

combobo <notifications@github.com>于2019年6月15日 周六13:22写道：

**Comment by hadix-lin** [comment]
升级到1.3.8支持该功能，可以自行[下载](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.8/ideavim_extension.zip)安装，也可以等插件中心更新。
