### ISSUE TITLE
在normal无法保持英文输入法

### ISSUE THREAD

**Issue by mano233** [hadix-lin/ideavim_extension#34]
操作系统:          macos10.14.6
idea版本:          2019.1.2
extension版本: 1.3.9
ideaVim版本:    0.53

使用:set keep-english-in-normal命令之后，我依然可以切换为中文输入法，我是哪里操作的不对吗？

**Comment by hadix-lin** [comment]
这个插件的作用是帮你在回到normal模式的时候切换到英文，不是在normal模式不允许切换输入法。

**Comment by mano233** [comment]
但是我看到issues中有提到这个需求https://github.com/hadix-lin/ideavim_extension/issues/19#issue-393824890，并且已经实现了。（可能和我想的不一样？）

**Comment by hadix-lin** [comment]
这个描述的是在每次输入焦点回到编辑器的时候如果识别当前输入状态是normal则自动切换为英文状态。
需要编辑器获得焦点事件来触发这个行为。

插件是永远不会阻止用户自己手动切换输入法的

**Comment by mano233** [comment]
谢谢，看来我误会了，很不错插件👍

**Comment by hadix-lin** [comment]
> 谢谢，看来我误会了，很不错插件👍

觉得好用，请给我star吧。
