### ISSUE TITLE
插件貌似会占用其他程序的热键

### ISSUE THREAD

**Issue by bmxbmx3** [hadix-lin/ideavim_extension#35]
intellij按esc进入command模式后，再切换到其他程序时，输入法不会自动切换回中文，chrome的快捷键也受到影响（比如ctrl+f无法弹出搜索框），即便win+space切换中文输入法后，输入字符依然有延迟，貌似会占用热键。

**Comment by hadix-lin** [comment]
ideavim_extension的输入法切换功能不会作用于IDEA之外的应用，且本身并没有占用注册任何热键，即使是ideavim本身注册的热键也仅在IDEA编辑器内有效，您所说的情况可能是由于您使用的输入法占用了热键，可以看一下您使用的输入法配置界面。

**Comment by bmxbmx3** [comment]
我的输入法是win原生的输入法，我查了输入法设置的快捷键，暂时没有找到冲突的地方。而且不打开插件的时候，chrome按ctrl+f不会受到影响，不清楚为什么。

**Comment by hadix-lin** [comment]
这样的话，我暂时也分析不出什么原因，ideavim_extension只是调用系统的api切换输入法，并没有做其他的，开着插件的时候chrome的ctrl+f就始终不能用吗？

**Comment by bmxbmx3** [comment]
经常是按很多下ctrl+f都没反应，而且切换到其他程序（比如chrome）上运行时，系统的输入法貌似会被锁定在英语输入法上，按shift也始终不能切换至中文，即便是ctrl+shift也不起作用。

**Comment by hadix-lin** [comment]
我没有windows环境，暂时没办法重现这个状况。请提供详细的重现步骤，我会找个环境尝试重现。

**Comment by hadix-lin** [comment]
无后续反馈，关闭。
