### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by koutselakismanos** [hadix-lin/ideavim_extension#37]
Ubuntu
phpstorm
![Screenshot from 2019-11-22 14-49-29](https://user-images.githubusercontent.com/23614722/69427113-80978f00-0d37-11ea-9fb2-d01b00cfd084.png)

**Comment by hadix-lin** [comment]
1.3.9版本与ideavim 0.54版本不兼容导致该问题。已经发布新版本，插件中心审核中。

急用请直接[下载新版本安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.0/ideavim_extension.zip)

**Comment by koutselakismanos** [comment]
@hadix-lin thanks!
