### ISSUE TITLE
开启新一行插入输入法无法恢复

### ISSUE THREAD

**Issue by tinyweet** [hadix-lin/ideavim_extension#38]
## 环境

- OS: Linux 4.19.85-1-MANJARO
- Intellij: IntelliJ IDEA 2019.2.4 (Ultimate Edition)
- IdeaVim: 0.54
- IdeaVimExtension: 1.4.0

## 命令
- o, O 无法恢复输入法

**Comment by hadix-lin** [comment]
感谢反馈，我会尽快尝试重现并修复该问题。

tinyweet <notifications@github.com>于2019年11月26日 周二11:45写道：

**Comment by hadix-lin** [comment]
问题已修正可以自行[下载更新](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.1/ideavim_extension.zip)，或者等插件中心审核通过后检查更新。
