### ISSUE TITLE
Incorrect input method restoration

### ISSUE THREAD

**Issue by blaxpy** [hadix-lin/ideavim_extension#39]
Found two problems regarding input method restoration.

IdeaVim 0.54
IdeaVimExtension 1.4.0
fcitx 4.2.9.6

![Input Method Configuration](https://imgur.com/gSHrAiN.png)

---

#### Changing vi mode to insert mode by pressing `i` always changes the input method to `ru`.

Steps to reproduce:
1. Add `:set keep-english-in-normal-and-restore-in-insert` to `~/.ideavimrc`
2. Change to the insert mode by pressing `i`. The input method is automatically changed to `ru`.
3. Manually change the input method to `us`.
4. Exit the insert mode.
5. Enter the insert mode by pressing `i`. Input method is automatically changed to `ru`.

Expected behaviour:
After changing to the insert mode by pressing `i` the input method is automatically changed to `us`.

---

#### Changing vi mode to insert mode by pressing `o` or `O` does not restore the input method.

Steps to reproduce:
1. Add `:set keep-english-in-normal-and-restore-in-insert` to `~/.ideavimrc`
2. Change to the insert mode by pressing `i`. The input method is automatically changed to `ru`.
3. Exit the insert mode.
4. Change to the insert mode by pressing `o`. The input method is not changed and is equal to `us`.

Expected behavior:
After changing to the insert mode by pressing `o` the input method is automatically changed to `ru`.

---

Plugin [fcitx.vim](https://github.com/lilydjwg/fcitx.vim) also uses fcitx to change the input method and has the behavior described in the 'Expected behavior' sections.

**Comment by blaxpy** [comment]
I examined [fcitx.py](https://github.com/lilydjwg/fcitx.vim/blob/master/plugin/fcitx.py) in fcitx.vim repository and found out the following:
1) The plugin calls deactivate (`switchToEnglish`) method only when the `fcitx state == 2` (2 for active) and then enables `inputtoggle` flag.
2) The plugin calls activate (`restore`) method only when `inputtoggle` flag is enabled.

Calling `fcitx-remote` without any arguments returns current `fcitx state`.

**Comment by hadix-lin** [comment]
The problem of "Changing vi mode to insert mode by pressing o or O does not restore the input method." is fixed in version 1.4.1 .

The other problem will be fixed in version 1.4.2 .

Thanks for your feedback !

**Comment by hadix-lin** [comment]
please [download](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.2/ideavim_extension.zip) the v1.4.2 , install then try it .

**Comment by blaxpy** [comment]
Tried it on PyCharm 2019.3.1 with a following line added to JVM options (fixes a [problem of input method switching via fcitx](https://youtrack.jetbrains.com/issue/JBR-2003?p=IDEA-227895)):
```
-Dauto.disable.input.methods=false
```
Everything works perfectly. Thank you for the fix.
