### ISSUE TITLE
我把系统英文输入法删除了，现在就用的搜狗，这样这个插件还用不上呢。。

### ISSUE THREAD

**Issue by Daopr** [hadix-lin/ideavim_extension#4]
另外你有没有遇到过，有时候需要按很多次esc才可以回到normal

**Comment by hadix-lin** [comment]
![image](https://cloud.githubusercontent.com/assets/1037389/26752958/519d74be-488e-11e7-8900-74f0e1e6ee26.png)

这个插件是依赖系统英文输入法的,不知道你是怎么设置的.如图,需要同时有系统的英文输入法和搜狗.

**Comment by hadix-lin** [comment]
@Daopr  按多次esc才可以回到normal的情况,没遇到过

**Comment by Daopr** [comment]
我是经常出现，不知道为什么，我在他家系列的任何软件里用 ideaVim，都会出现这个情况，你不用搜狗等类似的输入法吗？

**Comment by hadix-lin** [comment]
我也是用搜狗的.

把你的idea,ideaVim,ideaVimExtension的版本列出来,我试试能不能重现.

有一种情况是需要按两次esc才有效的.正在使用搜狗输入的时候,第一次按esc是退出当前输入,这个是输入法控制的.第二次才是ideaVim插件处理.

**Comment by Daopr** [comment]
好的，我晚上看一下^_^，如果你都没遇到过，那可能是我的rc文件的问题了

**Comment by hadix-lin** [comment]
还有就是如果当前的编辑器打开的是只读文件,那么也是不能esc切换到normal的.
