### ISSUE TITLE
用o,c进入编辑模式无法恢复之前的输入法

### ISSUE THREAD

**Issue by lhyqy5** [hadix-lin/ideavim_extension#40]
## 版本信息
IdeaVim 0.54
IdeaVimExtension 1.4.0
另外安装了IdeaVim-EasyMotion 1.0

## .ideavimrc内容
```
set multiple-cursors
set keep-english-in-normal-and-restore-in-insert
set easymotion
set surround
set commentary
```

**Comment by hadix-lin** [comment]
1.4.1版本修复了该问题。

另外借问一句，easymotion使用起来是什么效果，我安装配置后没啥用。acejump我也安装了。

**Comment by lhyqy5** [comment]
我刚试了下1.4.1,oO进入编辑的问题已经好了,不过用c进入编辑模式还是不行

easymotion我也刚开始用,感觉还行,要触发需要按两下`\`键,然后再用常规的跳转
比如
`\`+`\`+`s`+`<一些字符>`

**Comment by hadix-lin** [comment]
这个使用方式不如自己把autojump的快捷键映射到"<normal>f"上，感觉更自然

**Comment by hadix-lin** [comment]
c进入编辑模式的问题，会在1.4.2尝试修正。

**Comment by hadix-lin** [comment]
v1.4.2 版本修正c进入编辑模式不能恢复输入法的问题，[请下载](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.2/ideavim_extension.zip)试用。

**Comment by lhyqy5** [comment]
更新1.4.2后没问题了
