### ISSUE TITLE
keep-english-in-normal-and-restore-in-insert 下的一个现象

### ISSUE THREAD

**Issue by tinyweet** [hadix-lin/ideavim_extension#41]
## 环境
- OS: Linux 4.19.85-1-MANJARO
- Intellij: IntelliJ IDEA 2019.3 (Ultimate Edition)
- IdeaVim: 0.54
- IdeaVimExtension: 1.4.1
- ideavimrc 配置: set keep-english-in-normal-and-restore-in-insert
- 输入法
    - 中文: fcitx-googlepinyin
    - 英文: Keyboard - English(US)

## 操作步骤如下
1. 在normal 模式下, 按 i 进入 insert 模式; 切换输入法为 googlepinyin, 然后输入中文; 输入完成后, 切换输入法为 Keyboard - English(US), 然后按 esc 切换到 normal 模式
2. 按 i 再次进入 insert 模式, 输入法依然是 googlepinyin

## 个人理解
上述的操作步骤, 最终是否为 English(US) 输入状态?

**Comment by hadix-lin** [comment]
当前是有这个逻辑，当前输入法不为英文才保存。你说的情况似乎更合理，下个版本我改一下

tinyweet <notifications@github.com>于2019年12月5日 周四16:24写道：

**Comment by hadix-lin** [comment]
应该是只有linux有这个问题，1.4.2尝试修正这个问题。

**Comment by hadix-lin** [comment]
v1.4.2 修复该问题，[请下载](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.2/ideavim_extension.zip)试用。

**Comment by tinyweet** [comment]
> v1.4.2 修复该问题，[请下载](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.2/ideavim_extension.zip)试用。

问题修复

**Comment by wanglongbiao** [comment]
好像对小狼毫输入法不起作用，我是 win10系统。

**Comment by hadix-lin** [comment]
> 好像对小狼毫输入法不起作用，我是 win10系统。

你遇到的问题是？

**Comment by hadix-lin** [comment]
长时间未收到反馈

**Comment by wanglongbiao** [comment]
> 好像对小狼毫输入法不起作用，我是 win10系统。

可以使用了，之前没有配置英文语言，谢谢。
