### ISSUE TITLE
Webstorm 2019.3 版本，没有生效

### ISSUE THREAD

**Issue by suyulin** [hadix-lin/ideavim_extension#43]
插件都是最新版本：
idea vim : 0.54
ideavim_extension : 1.4.1
![image](https://user-images.githubusercontent.com/6275411/70767278-98dd5580-1d9b-11ea-9663-56056471e92a.png)
也可以通过将set keep-english-in-normal[-and-restore-in-insert]加入到~/.ideavimrc文件中并重启IDE来启用插件功能。 这个配置不会生效
:set keep-english-in-normal 开启输入法自动切换功能  这个方法是有效的。
老版本的功能都是自动开启的，新版本好像没有开启。

**Comment by hadix-lin** [comment]
set keep-english-in-normal

有使用这个指令吗？

**Comment by suyulin** [comment]
> set keep-english-in-normal
> 
> 有使用这个指令吗？

更新了一下说明。使用 set keep-english-in-normal 命令是有效的，但是老版本不用手动启用

**Comment by hadix-lin** [comment]
> > set keep-english-in-normal
> > 有使用这个指令吗？
> 
> 更新了一下说明。使用 set keep-english-in-normal 命令是有效的，但是老版本不用手动启用

新版本使用了IdeaVim其他的官方扩展一致的策略，把这个默认启用去掉了。
