### ISSUE TITLE
退格键会导致进入中文的奇怪bug

### ISSUE THREAD

**Issue by ArchCST** [hadix-lin/ideavim_extension#44]
### 系统信息
系统：MacOS Catalina
版本：2019.3 ultimate edition
设置：`:set keep-english-in-normal-and-restore-in-insert`
输入法：Rime

### Bug 重现：
![CleanShot 2019-12-18 at 13 24 15](https://user-images.githubusercontent.com/41679407/71058132-c6f6d700-2199-11ea-9ff6-f72655bfaaca.gif)
```
1. 先于 insert-mode 中切换到中文输入法
2. 按 esc 进入 normal-mode
3. 按 o 进入 insert-mode，此时为中文输入法
4. 切换到英文输入法
5. 输入任意长度字符（"asd"），按退格键（删除"d"），bug出现：变成了中文输入法（注意状态栏的输入法图标）
6. 打字出现中文（"工"）。
```

> 第三步中，用 o、O、a、i 均会出现此bug。
> 为排除输入法的原因，我换成了 macOS 原生输入法并重新编译了 fcitx-remote，bug 依旧存在。

**Comment by hadix-lin** [comment]
收到，近日我会调试一下，周末应该有时间处理。

**Comment by runforprogram** [comment]
在Android Studio 3.5上也是如此。研究一下，应该是退格键触发了restore方法，切换为上一次insert mode的输入法了。不熟悉插件开发的api，没有找到合适的文档。暂时不知道怎么改。

**Comment by hadix-lin** [comment]
1.4.3修正该问题，可以自行[下载安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.3/ideavim_extension.zip)试用。
