### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kobe1329989713** [hadix-lin/ideavim_extension#47]

**Comment by hadix-lin** [comment]
建议内容呢？

**Comment by kobe1329989713** [comment]
就是可以参考下 gVim 里面的那种切换嘛，我觉得gVim 的那个切换真的是太好了，而且一个输入法也能进行切换。

**Comment by kobe1329989713** [comment]
按 ESC键后还可以自动映射一个 shift键，我尝试使用 ideavim映射 shift键。就是映射不了。

**Comment by hadix-lin** [comment]
我也有想过，但是实现起来有很多解决不了的问题

1.
输入法的shift是切换输入状态，且不同输入法未必开放了控制api，shift按键操作之后的状态插件无法获取。这样就无法保障shift操作够一定能切换到预期状态
2.目前没有找到可以直接向操作系统发送键盘输入指令的api

问题1是难点，问题2花时间找资料应该还是可以找到的，因为我自己不熟悉操作系统的api所以时间成本会比较高


kobe <notifications@github.com>于2020年1月23日 周四19:35写道：
