### ISSUE TITLE
从normal模式切换到其他程序后，切回idea再进入insert模式不能恢复为中文输入法

### ISSUE THREAD

**Issue by lu5je0** [hadix-lin/ideavim_extension#48]
用的是set keep-english-in-normal-and-restore-in-insert，另外就是设置了win10的不同窗口使用不同的输入法

**Comment by hadix-lin** [comment]
收到，我尝试重现一下看看

**Comment by lu5je0** [comment]
_da6b1f946279e9336dffee4fb43f7e736f90e58b_，我发现这样可以解决这个问题，你可以参考一下

**Comment by kobe1329989713** [comment]
我按照你说的方法重新构建了还是不行了， 只有在插入模式下切换才是正常的。我的是windows10系统。

**Comment by hadix-lin** [comment]
> _[da6b1f9](https://github.com/hadix-lin/ideavim_extension/commit/da6b1f946279e9336dffee4fb43f7e736f90e58b)_，我发现这样可以解决这个问题，你可以参考一下

这样改的话会带来另外一个问题 https://github.com/hadix-lin/ideavim_extension/issues/41

**Comment by hadix-lin** [comment]
1.4.4版本解决该问题，可以直接在插件中心下载试用。
