### ISSUE TITLE
idea闪退

### ISSUE THREAD

**Issue by lonenol** [hadix-lin/ideavim_extension#5]
最新系统,最新idea,最新ideavim,最新插件
会导致idea闪退,关闭该插件后就没有出现过,应该是这个插件导致的

**Comment by hadix-lin** [comment]
这个我也有遇到，在连续快速操作时会发生，具体原因还没分析出来。如果您能提供更多线索当然是最好的

**Comment by lonenol** [comment]
是不是记录输入法状态的堆栈溢出了啊....

**Comment by hadix-lin** [comment]
长时间使用后没有再发生过闪退的问题.以下是我的idea.vimoptions

-server
-Xms2048m
-XX:ReservedCodeCacheSize=240m
-XX:+UseCompressedOops
-XX:+UseCodeCacheFlushing
-XX:+UseConcMarkSweepGC
-XX:+AggressiveOpts
-XX:+CMSClassUnloadingEnabled
-XX:+CMSIncrementalMode
-XX:+CMSIncrementalPacing
-XX:CMSIncrementalDutyCycleMin=0
-XX:-TraceClassUnloading
-XX:+TieredCompilation
-Xmx4096m
