### ISSUE TITLE
回到插入模式时仍然是英文输入法

### ISSUE THREAD

**Issue by zydxhs** [hadix-lin/ideavim_extension#50]
满怀期待的安装这个插件，尝试后感觉鸡肋。
Win10 LTSC 2019 + CLion + IdeaVim + IdeaVimExtension，安装两个中文输入法。
在插入模式切换到中文输入法，ESC 回到 normal 模式，进入预期的英文状态；I 再进入插入模式，还是英文输入状态。
> 按照说明，尝试了这两个选项： `keep-english-in-normal-and-restore-in-insert` 和 `nokeep-english-in-normal-and-restore-in-insert`，同样的结果。

**Comment by hadix-lin** [comment]
set keep-english-in-normal-and-restore-in-insert

应该是可以恢复输入法到原来的状态的，如果没有请报告bug。

我自己是不使用keep-english-in-normal-and-restore-in-insert这个选项的因为编程中的大部分场景不需要恢复回英文输入法，所以对这个特性的测试并不充分。

nokeep-english-in-normal-and-restore-in-insert 这个选项是关闭特性
