### ISSUE TITLE
插件不能切换搜狗中文输入法

### ISSUE THREAD

**Issue by vcjmhg** [hadix-lin/ideavim_extension#53]
# 概述
您好，我按照制定配置，配置完插件以后，发现该切换功能大部分情况下是不好用的
# 环境
window 7 64bit,goland,搜狗输入法
# 具体问题
具体使用过程中我在.ideavimrc配置的代码如下：
![image](https://user-images.githubusercontent.com/55177318/82807548-8e7ec600-9eba-11ea-817d-ec6c24ebaf3b.png)
但是用过程中发现，进入normal模式下不能够自动切换到英文输入法
![结果](https://user-images.githubusercontent.com/55177318/82807570-9c344b80-9eba-11ea-9deb-9b465577010f.gif)
**不知是我配置有问题，还是因为不太支持win7环境或者我该如何修改才能让插件正常工作，谢谢！**

**Comment by hadix-lin** [comment]
有有开启系统默认的英文输入法吗？

win7我并没有测试过，理论上是支持的，我自己的开发环境是mac

vcjmhg <notifications@github.com>于2020年5月25日 周一19:06写道：

**Comment by hadix-lin** [comment]
这个插件是不能切换搜狗输入法的中英文模式的，只能从搜狗输入法切换到系统的英文输入法。

搜狗没有开放切换模式的API，插件做不了。

**Comment by vcjmhg** [comment]
您好，系统的中文输入法是开启着的
![image](https://user-images.githubusercontent.com/55177318/82973777-e0cefc80-a00a-11ea-97b1-59823a49afc7.png)
使用的是中文简体美式键盘。

**Comment by hadix-lin** [comment]
.ideavimrc 中其他的指令都生效吗？

**Comment by hadix-lin** [comment]
请提供一下您使用的IDE版本，ideavim，ideavim_extension版本，我找个环境重现一下。

**Comment by vcjmhg** [comment]
您好，`.ideavimrc`的其他指令都可以正常工作。我在命令模式下输入`:set keep-english-in-normal-and-restore-in-insert`依然是不能正常工作的。
 关于IDE其实我试了IDEA和GoLand的最新版本，好像都不太能工作。
**我的IDE版本和插件版本对应截图如下：**
![image](https://user-images.githubusercontent.com/55177318/82980924-43c98f00-a01d-11ea-9f61-d87a61483511.png)
![image](https://user-images.githubusercontent.com/55177318/82980966-5fcd3080-a01d-11ea-8f34-0d318052334c.png)
![image](https://user-images.githubusercontent.com/55177318/82980985-6b205c00-a01d-11ea-8db7-1bfa25c965dc.png)

**搜狗输入法版本如下：**
![image](https://user-images.githubusercontent.com/55177318/82981202-fef22800-a01d-11ea-8d63-cf2b8209abe9.png)

**`.ideavimrc`文件的内容如下:**
``` lua
" 将查找功能替换为idea的自带的查找功能
noremap / :action Find<CR>
set showmode
set clipboard=unnamed
" 映射idea常用快捷键
" 重命名
nnoremap <leader>r :action RenameElement<CR>
" 格式化当前文件
nnoremap <leader>f :action ReformatCode<CR><esc>
" quick java doc
nnoremap <leader>q :action QuickJavaDoc<CR>

" 插件模拟
" surround
set surround
" multiple-cursors
set multiple-cursors
" easyMotion 模拟，额外依赖插件：AceJump,IdeaVim-EasyMotion
set easymotion
" 注释插件模拟
set commentary
set clipboard+=ideaput
" 设置vim进入normal模式后自动切换到英文输入法，进入到Insert模式后切换为原来的输入法
set keep-english-in-normal-and-restore-in-insert
```

**Comment by hadix-lin** [comment]
没有windows环境进行重新，无法解决该问题，抱歉。
