### ISSUE TITLE
normal 模式不能切换到英语输入，但是insert模式的restore是有效果的。。。

### ISSUE THREAD

**Issue by liangjihua** [hadix-lin/ideavim_extension#56]
在normal模式下切换输入法，进入insert模式会restore，但是在insert模式下切换输入法再esc到normal模式不会自动切换输入法到英语。idea event log也没有报错。
配置：
![图片](https://user-images.githubusercontent.com/35123083/95801889-663f1900-0d2e-11eb-92ee-70e1ba9b840c.png)
![图片](https://user-images.githubusercontent.com/35123083/95801966-b6b67680-0d2e-11eb-8fe9-d6d09c41fe86.png)
idea： 2020.02
ideavim_extension: 1.4.7

**Comment by hadix-lin** [comment]
去掉倒数第二个指令试试

Yu Jiaxin <notifications@github.com>于2020年10月13日 周二08:36写道：

**Comment by liangjihua** [comment]
我把英语键盘删了重加可以了。
