### ISSUE TITLE
似乎跟 ideavim 0.61 版本冲突

### ISSUE THREAD

**Issue by weiwee** [hadix-lin/ideavim_extension#58]
使用的配置项：
`set keep-english-in-normal`

现象：
启动PyCharm的时候ideavim失效，手动在tool里面勾选掉后再勾选可恢复正常

**Comment by lianfanghua** [comment]
java.lang.NoSuchMethodError: 'void com.maddyhome.idea.vim.extension.VimExtensionFacade.putKeyMapping(java.util.Set, java.util.List, java.util.List, boolean)'

**Comment by hadix-lin** [comment]
等我更新一下

**Comment by hadix-lin** [comment]
> 重新安装不报错，然后重启idea后就报错了
> 
> ```
> java.lang.NoSuchMethodError: 'void com.maddyhome.idea.vim.extension.VimExtensionFacade.putKeyMapping(java.util.Set, java.util.List, java.util.List, boolean)'
> ```

IdeaVim 0.61删除了这个API，需要适配一下

**Comment by hadix-lin** [comment]
请下载最新版本
https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.8/ideavim_extension.zip
