### ISSUE TITLE
无法再输入中文

### ISSUE THREAD

**Issue by lonenol** [hadix-lin/ideavim_extension#6]
搜狗输入法.用一段时间后,就没法输入中文了.会用idea打开终端功能

**Comment by hadix-lin** [comment]
这个问题没遇到过，请问能提供具体的复现步骤吗？

**Comment by lonenol** [comment]
用着用着就出来了,还真不知道咋出现的的,
写代码代码以外的操作就是会用optional+f12呼出终端执行一些git和maven命令,不知道是不是这个导致的

**Comment by hadix-lin** [comment]
无法重现该问题,如有线索请重新提交该问题.
