### ISSUE TITLE
希望支持单输入法下的中英文自动切换

### ISSUE THREAD

**Issue by bluer007** [hadix-lin/ideavim_extension#61]
你好, 本人无意中发现了这个插件, 出发点挺好的, 但是发现在我win10的输入法配置下失效, 我猜测的原因是我只有一个百度输入法, 没有英式键盘,, 导致该插件不知道怎么切换到英文
   所以希望作者能不能支持下该设置呢?  或者允许用户自定义动作键, 如进入normal模式后, 自动触发shift键, 让百度输入法进入英文模式, 回到insert模式, 又自动触发shift键, 让进入原来的中文模式?  当然如果百度输入法有中英文对应的快捷键就最好了, 希望作者可以考虑下

![image](https://user-images.githubusercontent.com/10069870/103498795-e33ae400-4e80-11eb-9421-7d04f6df0671.png)

![image](https://user-images.githubusercontent.com/10069870/103498804-eb931f00-4e80-11eb-9992-464dac1adf68.png)

**Comment by hadix-lin** [comment]
插件说明中有写需要开启英文输入法才能切换。

我也想使用输入法自带的切换能力，但绝大部分输入法是没有开放这个api给外部调用的，所以实现不了。

现在的实现原理是利用操作系统自己的输入法切换功能实现。

如果您有其他的思路来实现该功能，我们可以讨论一下。
