### ISSUE TITLE
希望以后作者有机会能开发一个vscode的vim中文插件

### ISSUE THREAD

**Issue by joyous-coder** [hadix-lin/ideavim_extension#63]
如题，现在vscode上也提供了解决方案，是调用一个exe程序实现的切换，处理中文切换的方法和你的差不多，也是双输入法来回切换，但装上后这个切换模式的响应速度是非常的慢。和你在idea上的插件差很多。希望有机会能看见你的插件。

**Comment by hadix-lin** [comment]
vscode我不是很熟悉，清发一下vscode的解决方案给我看一下。

idea插件的实现是用JNA调用本地方法实现的，不需要fork进程，可能是因为这个更快。我不了解vscode的机制，不知道有没有方便得调用本地方法的机制。

**Comment by joyous-coder** [comment]
![image](https://user-images.githubusercontent.com/42910684/106419781-2f833f00-6494-11eb-8a7a-ca561d6a526c.png)
不是很了解这个功能的底层实现。  https://github.com/VSCodeVim/Vim#input-method，这个是配置方法

**Comment by hadix-lin** [comment]
> ![image](https://user-images.githubusercontent.com/42910684/106419781-2f833f00-6494-11eb-8a7a-ca561d6a526c.png)
> 不是很了解这个功能的底层实现。 https://github.com/VSCodeVim/Vim#input-method 这个是配置方法

这个是利用im-select实现的，应该是调用系统命令行去实现的，应该也不会慢很多的，现在电脑CPU频率都那么高了。

你说的非常慢是到啥程度，需要1秒才能自动切换？

**Comment by joyous-coder** [comment]
感觉得有一秒，没有你的哪个插件那么迅速。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hadix"<notifications@github.com&gt;; 
发送时间: 2021年2月1日(星期一) 下午4:48
收件人: "hadix-lin/ideavim_extension"<ideavim_extension@noreply.github.com&gt;; 
抄送: "王昱斌"<joyous-coder@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hadix-lin/ideavim_extension] 希望以后作者有机会能开发一个vscode的vim中文插件 (#63)





  

 不是很了解这个功能的底层实现。 https://github.com/VSCodeVim/Vim#input-method 这个是配置方法
  
这个是利用im-select实现的，应该是调用系统命令行去实现的，应该也不会慢很多的，现在电脑CPU频率都那么高了。
 
你说的非常慢是到啥程度，需要1秒才能自动切换？
 
&mdash;

**Comment by ifnk** [comment]
> 感觉得有一秒，没有你的哪个插件那么迅速。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hadix"<notifications@github.com&gt;; 发送时间: 2021年2月1日(星期一) 下午4:48 收件人: "hadix-lin/ideavim_extension"<ideavim_extension@noreply.github.com&gt;; 抄送: "王昱斌"<joyous-coder@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hadix-lin/ideavim_extension] 希望以后作者有机会能开发一个vscode的vim中文插件 (#63) 不是很了解这个功能的底层实现。 https://github.com/VSCodeVim/Vim#input-method 这个是配置方法 这个是利用im-select实现的，应该是调用系统命令行去实现的，应该也不会慢很多的，现在电脑CPU频率都那么高了。 你说的非常慢是到啥程度，需要1秒才能自动切换？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你是用 windows 系统么？ 如果是windows 系统 可以 采用 ahk 映射 ,当按esc 的情况下 ,强制将 输入法切换 成 英文 呢
