### ISSUE TITLE
能不能支持colemak输入法啊...

### ISSUE THREAD

**Issue by kackerx** [hadix-lin/ideavim_extension#67]
能不能支持colemak输入法啊..., 试了试只能换回英文, 我是使用mac的colemak输入法能支持不, 谢谢大佬

**Comment by hadix-lin** [comment]
colemak,这个我还没用过，等我试用一下

**Comment by hadix-lin** [comment]
colemak 这只是一种键盘布局啊，建议你通过karabiner来实现，而不是替代的输入法产品。

理论上任何键盘布局上都可以实现输入英文或中文，你现在的方案应该只能输入英文吧？

**Comment by Miemiemiemieqiang** [comment]
![image](https://user-images.githubusercontent.com/39361661/142573659-672a2047-1368-4473-973e-05e43b2f3de5.png)
希望能通过这种方式来在普通模式设置 colemak 布局

**Comment by hadix-lin** [comment]
你可以试一下这个指令，在.ideavimrc文件中
set keep_input_source_in_normal="com.apple.keylayout.Colemak"
