### ISSUE TITLE
idea 2021.1中IdeaVimExtension插件配置后不起作用

### ISSUE THREAD

**Issue by yao-aiqing** [hadix-lin/ideavim_extension#68]
在idea 2021 for mac 中，IdeaVimExtension插件配置后不起作用，已经开始了ABC输入法，
已经在.ideavim配置文件中开始了set nokeep-english-in-normal-and-restore-in-insert配置。

**Comment by hadix-lin** [comment]
应该是set keep-english-in-normal-and-restore-in-insert，没有no

有no开头表示关闭该功能

**Comment by hadix-lin** [comment]
还有配置文件应该是.ideavimrc
