### ISSUE TITLE
IdeaVimExtension

### ISSUE THREAD

**Issue by barryzhao823** [hadix-lin/ideavim_extension#73]
![image](https://user-images.githubusercontent.com/48462978/126035125-4ab58eab-7689-4335-a737-465ed324a9f2.png)

**Comment by hadix-lin** [comment]
不影响功能使用，下个版本会修正这个问题

**Comment by hadix-lin** [comment]
#72

**Comment by hadix-lin** [comment]
Duplicate of #72

**Comment by hadix-lin** [comment]
1.4.12修正该问题
