### ISSUE TITLE
能否支持切屏（切到其他应用程序）时自动恢复输入法

### ISSUE THREAD

**Issue by GsssC** [hadix-lin/ideavim_extension#74]
如题。每次切到IDE输入法就被设为英语（美国），再切到聊天软件没有自动恢复，需要手动恢复。

**Comment by hadix-lin** [comment]
插件是在IDE内生效的只能作用域编辑器，现在的实现机制是在编辑器获取到焦点以及VIM状态变化的时候自动变更输入法。

你这个需求或许可以通过监听编辑器失去焦点的事件来实现，我考虑一下。

**Comment by hadix-lin** [comment]
不过通过这个方式，只能切换输入法到上次切换之前。

例如，聊天软件（搜狗-文中）->进入IDE编辑器（英文）这个没问题，再切换回聊天软件的时候就还是（搜狗-中文）
聊天软件（搜狗-文中）->进入IDE编辑器（英文）->
自行切换到（搜狗-中文）编写注释->自行切换到英文编写代码->切换到聊天软件就不会切到（搜狗-中文）

**Comment by hadix-lin** [comment]
mac 应该可以通过这个配置来实现
![image](https://user-images.githubusercontent.com/1037389/133745230-86873e59-b1b1-4a42-a95b-1c8d6970a49f.png)
