### ISSUE TITLE
支持更多模式切换

### ISSUE THREAD

**Issue by mask-zpt** [hadix-lin/ideavim_extension#75]
能支持  " v V  <C-v>  命令模式 " 的进入和退出自动切换为英文输入法吗

**Comment by hadix-lin** [comment]
visual mode有没有输入中文的情况？我不是很熟悉

如果没有也是可以做自动切换的，可以尝试在下个版本加上这个

**Comment by hadix-lin** [comment]
仔细想一下这个模式应该是不存在的，要使用v V命令的前提是要ESC到normal模式，这就已经可以切换到英文输入法了

**Comment by mask-zpt** [comment]
命令模式 和  search 模式 是会用到的

**Comment by hadix-lin** [comment]
> 命令模式 和 search 模式 是会用到的

可以举个场景的例子吗

**Comment by mask-zpt** [comment]
比如搜索  "我是"  那就会输入   /我是

**Comment by hadix-lin** [comment]
> 比如搜索 "我是" 那就会输入 /我是

“/”可以正常进入搜索模式的，这时候是可以自行切换到中文输入法，搜索之后回到编辑器，可以自动切换回英文输入法
