### ISSUE TITLE
能否支持下ibus?

### ISSUE THREAD

**Issue by yuzhou721** [hadix-lin/ideavim_extension#76]
现在的环境是pop!_os 更换fcitx有点麻烦,想问问能否支持ibus?
切换的相关api很简单 
`ibus engine` 获取当前输入法状态
`ibus engine 输入法名称` 切换输入法
英文输入法固定就是 `xkb:us::eng`
其他输入法也是通过`ibus list-engine`可以看到 
`vscode`的`vim`插件是提供了3个变量的配置来实现:
1. 默认im
2. 获取当前输入法的命令
3. 切换输入法命令

**Comment by hadix-lin** [comment]
你提供的指令蛮详细的，不过我没有linux开发环境，比较难测试。

如果你可以fork一下我的代码，提交个PR，我可以尝试合并，否则就要等我找到合适的开发环境才行

**Comment by yuzhou721** [comment]
好的 之前没接触过插件开发 我试试

**Comment by hadix-lin** [comment]
> 好的 之前没接触过插件开发 我试试

需要代码上的帮助，可以邮件联系我，hadix.lin@gmail.com
