### ISSUE TITLE
切换回insert中文模式后输入中文符号问题

### ISSUE THREAD

**Issue by raylzhang** [hadix-lin/ideavim_extension#86]
系统是macos，英文是原生，中文是原生双拼，开启`set keep-english-in-normal-and-restore-in-insert`。每次从normal模式切换回insert模式（中文输入）后，输入符号，例如`（`、`，`、`）`等都会把前面一个字符替换掉。例如：`我是第一个提出这个问题的人`，我光标移动到`人`然后按`a`，再输入`。`，这时候`人`会被`。`替换掉。我一直都有这个问题，重装也没用。

**Comment by raylzhang** [comment]
我搜了之前closed状态的问题，发现和我一样的情况，macos原生双拼就有这个问题，我刚刚换成sogou输入法就正常了，我在vscode中使用它的autoswitch原生双拼没有问题呢。

**Comment by hadix-lin** [comment]
![image](https://user-images.githubusercontent.com/1037389/162376301-4c1233a0-361e-408d-8159-95705ff0d42e.png)
我没有复现这个问题

**Comment by raylzhang** [comment]
非常感谢!!我打开了`Use halfwidth punctuation`就能正常了,再次感谢🙏
