### ISSUE TITLE
根据上下文状态自动切换中英文

### ISSUE THREAD

**Issue by yuzhou721** [hadix-lin/ideavim_extension#88]
之前在emacs上用过类似的vim模式自动切换中英文的插件，能做到根据光标附近的中英文状态确定当前进入insert模式以后是中文还是英文，但是当前插件只能根据上次的输入法来切换，能否新增个特性？
大概这个思路
![image](https://user-images.githubusercontent.com/24775063/168869461-09ee3e25-dace-4666-9c0d-b74f6aaf73c7.png)

**Comment by hadix-lin** [comment]
v1.6.0

**Comment by yuzhou721** [comment]
貌似没起作用

**Comment by hadix-lin** [comment]
set keep-english-in-normal-and-restore-in-insert

配合这个配置使用

**Comment by yuzhou721** [comment]
当前环境：社区版2022.1.1 输入法：ibus 
晚上我回去试试fcitx是否可以
set keep-english-in-normal-and-restore-in-insert 这个配置已经设置过了 能切换到英文，但是在中文中间按i进入insert还是切换到了英文状态 如果fcitx可以的话有可能是我ibus部分的锅

**Comment by yuzhou721** [comment]
@hadix-lin 今天使用fcitx测试了一下 还是没生效

**Comment by hadix-lin** [comment]
看起来需要更复杂，精确的方法来识别状态，我再想想

**Comment by hadix-lin** [comment]
> 之前在emacs上用过类似的vim模式自动切换中英文的插件，能做到根据光标附近的中英文状态确定当前进入insert模式以后是中文还是英文，但是当前插件只能根据上次的输入法来切换，能否新增个特性？ 大概这个思路 ![image](https://user-images.githubusercontent.com/24775063/168869461-09ee3e25-dace-4666-9c0d-b74f6aaf73c7.png)

你发这张图是从什么地方来的，可以把来源地址发一下吗？

**Comment by yuzhou721** [comment]
https://github.com/laishulu/emacs-smart-input-source
一个emacs在vim模式下用来切换输入法的库

**Comment by seyoatda** [comment]
我理解是如果cursor两侧都是英文才自动转为英文模式。如果两侧至少有一边是中文都应该维持原来的状态。或者说把这个识别模式做成一个可配置项

**Comment by yuzhou721** [comment]
升级新版idea，终于用上了，验证没啥问题
