### ISSUE TITLE
不生效

### ISSUE THREAD

**Issue by answer185** [hadix-lin/ideavim_extension#9]
我的开发 环境 是webStorm 和 macBook pro
输入法是搜狗五笔和搜狗拼音
插件是通过webStorm安装的
.ideavimrc中也设置了
  set keep-english-in-normal
但是没有成功过
把输入法删除了，换成苹果自带的拼音也不行
还有什么特别的设置吗？

**Comment by hadix-lin** [comment]
需要开启苹果系统的英文输入法
yongjie <notifications@github.com>于2018年4月20日 周五19:27写道：

**Comment by answer185** [comment]
可以用了，非常感谢
