### ISSUE TITLE
能否将返回insert模式时根据当前输入位置的字符是否为ASCII来决策是否恢复输入法功能设置为非默认选项

### ISSUE THREAD

**Issue by syouSui** [hadix-lin/ideavim_extension#90]
感谢大佬的插件提供给大家的便捷!
我是一名使用了两年了的老用户! 最近更新到最新 1.6 版本后, 发现有时候切换到 Insert 却还是 ABC 输入法, 今天有时间了仔细研究了下, 发现是插件新特性. 
因为我是 英文+搜狗 双输入法用户, 并且搜狗默认是英文状态, 通过 R_SHIFT 切换中英, 而不会通过频繁 CTRL + SPACE 来切换两种输入法. 如此新特性一来, 导致我要想在空白位置输入中文, 需要先切换输入法, 再按 R_SHIFT,  对我这样的用户群体而言, 是多出来了一步变得繁琐.
目前已暂降到 1.5.2 版本, 如果方便的话, 还请大佬提供一个变量来手动控制是否开启此特性! 
感谢!👏🏻👏🏻👏🏻

**Comment by hadix-lin** [comment]
最近为自己的使用体验也不是很好，我尽快找时间优化。

**Comment by syouSui** [comment]
> 最近为自己的使用体验也不是很好，我尽快找时间优化。
> […](#)

👍🏻👍🏻👍🏻

**Comment by hadix-lin** [comment]
[IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/8954041/IdeaVimExtension.zip)
试试这个包，在ideavim.rc里面可以通过let context_aware=0关闭掉这个特性

可以安装后看一下插件的changelog，查看具体的使用说明，测试过之后，请给我提供反馈。

**Comment by syouSui** [comment]
> [IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/8954041/IdeaVimExtension.zip) 试试这个包，在ideavim.rc里面可以通过let context_aware=0关闭掉这个特性
> 
> 可以安装后看一下插件的changelog，查看具体的使用说明，测试过之后，请给我提供反馈。

不好意思, 今天才看到. 已尝试 1.6.2, 就是这个效果! 感谢!

set keep-english-in-normal-and-restore-in-insert
let context_aware=0
