### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by B-Tanvir** [hadix-lin/ideavim_extension#91]
Can you give same kind of feature Qwerty in normal mode Dvorak in insert mode. It'll be very useful for Dvorak users.

**Comment by B-Tanvir** [comment]
It works

**Comment by hadix-lin** [comment]
![image](https://user-images.githubusercontent.com/1037389/174693455-7a49d728-9549-41f2-b75b-86335ec99ddf.png)

this？

**Comment by B-Tanvir** [comment]
Yes.

**Comment by hadix-lin** [comment]
Why not always use only Dvorak in both normal and insert mode?

**Comment by hadix-lin** [comment]
[IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/8954810/IdeaVimExtension.zip)

with tihs , you can :
controll plugin behavior in ideavim.rc via the following three variables:<br/>
        <code>let keep_input_source_in_insert=[input source id]</code> set input method for non-English used in insert mode<br/>
        <code>let keep_input_source_in_normal=[input source id]</code> set input method for English used in normal mode<br/>
        Note: The above two variables are only valid in windows and macOS<br/>
        <code>let context_aware=1</code> When entering insert mode, judge whether to restore the input method according to the context, 0 to disable, 1 to enable<br/>
        Note: Only meaningful <code>when set keep-english-in-normal-and-restore-in-insert</code><br/>

**Comment by hadix-lin** [comment]
[1.6.2](https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.2) 修正
