### ISSUE TITLE
插件中英文切换不稳定

### ISSUE THREAD

**Issue by allworldg** [hadix-lin/ideavim_extension#92]
version：win11 , idea2022.1.2 , ideavimExtension 1.6.2
在ideavimrc设置了`set keep-english-in-normal-and-restore-in-insert`之后，中文Insert模式切换到英文normal模式正常，但是再切换到insert模式大概率还是英语键盘。

**Comment by liyzcj** [comment]
version 1.6.2 macos
同样的问题，试了一下，在中文之间进入插入模式会恢复输入法，其他情况都不行。

以为是上下文功能的问题，但是使用 `let context_aware=1` 关闭了上下文功能也不行

**Comment by hadix-lin** [comment]
context_aware=1是启用，0才是关闭。

**Comment by hadix-lin** [comment]
> version：win11 , idea2022.1.2 , ideavimExtension 1.6.2 在ideavimrc设置了`set keep-english-in-normal-and-restore-in-insert`之后，中文Insert模式切换到英文normal模式正常，但是再切换到insert模式大概率还是英语键盘。

你可以试一下再.ideavimrc中增加配置 let context_aware=0，这个要配置在set keep-english-in-normal-and-restore-in-insert 之前

**Comment by allworldg** [comment]
@hadix-lin 增加了后初步试了一下，目前比较稳定，感谢。
ps: 插件默认启用上下文判断吗？

**Comment by bushnerd** [comment]
Mark一下，我也碰上同样的问题了。一会儿回去试试。

**Comment by bushnerd** [comment]
> @hadix-lin 增加了后初步试了一下，目前比较稳定，感谢。 ps: 插件默认启用上下文判断吗？

解决了。我记得之前是OK的，那么就是context_aware这个feature引入了问题？

**Comment by bushnerd** [comment]
> > @hadix-lin 增加了后初步试了一下，目前比较稳定，感谢。 ps: 插件默认启用上下文判断吗？
> 
> 解决了。我记得之前是OK的，那么就是context_aware这个feature引入了问题？

还发现一个问题，第一次进入insert模式，需要自己切换为中文输入法。后面就正常了。

**Comment by hadix-lin** [comment]
收到

**Comment by hadix-lin** [comment]
> > @hadix-lin 增加了后初步试了一下，目前比较稳定，感谢。 ps: 插件默认启用上下文判断吗？
> 
> 解决了。我记得之前是OK的，那么就是context_aware这个feature引入了问题？

的确是这样的，因为现在没有提供设置非英文输入法的方式，所以需要自己切换一次，让插件自动记录使用的中文输入法。
我觉得这种方式比提供一个设置来说，使用门槛儿更低。

**Comment by hadix-lin** [comment]
let keep_input_source_in_insert=[input source id] 

可以通过这个配置在ideavimrc文件中设置，插入模式使用的非英文输入法
input source id 可以通过 [imselect](https://github.com/daipeihust/im-select) 来获取

**Comment by bushnerd** [comment]
> let keep_input_source_in_insert=[input source id]
> 
> 可以通过这个配置在ideavimrc文件中设置，插入模式使用的非英文输入法 input source id 可以通过 [imselect](https://github.com/daipeihust/im-select) 来获取
> 
> 例如在mac系统下，input source id 是一个字符串，我使用的是系统自带的双拼输入法，通过imselect得到的值是com.apple.inputmethod.SCIM.Shuangpin 那么ideavimrc 中添加`let keep_input_source_in_insert="com.apple.inputmethod.SCIM.Shuangpin"`
> 
> 如果在windows系统下，input source id是一个数字，假设通过imselect得到的值是48668993 那么ideavimrc 中添加`let keep_input_source_in_insert=48668993"'
> 
> linux系统下不支持该配置

感谢，已经测试OK，这下不用手动切换一次了。

**Comment by hadix-lin** [comment]
对的，默认启用
