### ISSUE TITLE
每次在IDEA中运行代码，都会自动切换到中文

### ISSUE THREAD

**Issue by liangjihua** [hadix-lin/ideavim_extension#93]
环境：
 - manjaro linux
 - fcitx5
 - idea 2022.2

每次在idea中运行任意代码，包括使用鼠标点击 `Run`、快捷键运行 `Run`、或者运行 groovy console，甚至 http client 都会自动将输入法切换到中文，不论当前是 normal 模式还是 insert 模式。
配置：
```vim
let context_aware=1
set keep-english-in-normal
```

**Comment by hadix-lin** [comment]
收到

**Comment by hadix-lin** [comment]
> 环境：
> 
> * manjaro linux
> * fcitx5
> * idea 2022.2
> 
> 每次在idea中运行任意代码，包括使用鼠标点击 `Run`、快捷键运行 `Run`、或者运行 groovy console，甚至 http client 都会自动将输入法切换到中文，不论当前是 normal 模式还是 insert 模式。 配置：
> 
> ```viml
> let context_aware=1
> set keep-english-in-normal
> ```

你可以试一下这个版本[1.6.3](https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.3)，由于我没有Linux环境，所以无法测试，你可以先试一下，有问题再反馈。
