### ISSUE TITLE
进入搜索模式后，输入法能否切换为中文，与进入Insert模式一样。

### ISSUE THREAD

**Issue by bushnerd** [hadix-lin/ideavim_extension#94]

**Comment by hadix-lin** [comment]
可以改一下，按进入insert模式的行为处理，预估有以下问题。
进入搜索模式之后，大部分的需求是否是输入中文？这在写大段中文注释时可能才有用，但是考虑写代码主要还是使用英文，自动转换成中文输入维护时最好的选择
由于进入搜索模式时，没有可以参考的上下文，所以也没办法根据上下去推断使用什么输入法更好。

这是个很难判断的问题？为什么在你的使用场景里面，进入搜索模式更多是输入中文呢？

**Comment by bushnerd** [comment]
我的使用场景中，进入搜索模式后搜索中文的也不多。
我只是发现如果进入搜索模式后，如果需要输入中文的话，需要手动切换为语言，而不像进入Insert模式。

现在我的使用模式是：
1033，英语（美式键盘）
2052，QQ拼音输入法（默认为英文）

而ideavim_extension是在1033和2052之间切换，事实上我每次进入Insert模式后，如果需要输入法中文，需要手动在QQ拼音输入法中按下Shift(中英文输入切换键)进行切换的。

之前在这个[issue](https://github.com/daipeihust/im-select/issues/7)中讨论过，能否切换时保留QQ输入法的中英文状态，后来发现不行，事实上我对这个需求并不是那么强烈。
