### ISSUE TITLE
版本 1.6.4 卡顿

### ISSUE THREAD

**Issue by daroubing** [hadix-lin/ideavim_extension#96]
mac book pro 2015, rider 2022.2.2, 升级到 1.6.4 卡顿, 还原到 1.6.3 没问题
- vim normal 模式下, 鼠标在左右两个窗口交替点击卡顿

.ideavimrc 配置
set keep-english-in-normal

**Comment by jackytang** [comment]
我在昨天晚上更新以后, 打开工程没有两分钟就一直处于未响应状态, 根本没有办法使用, 禁用插件后正常, 可以确定就是这个版本的问题, 1.6.3用了很久也没有出现过这个问题

**Comment by ltxlouis** [comment]
我也是, 卡的不行

**Comment by mnkoua** [comment]
macbook pro最新系统，1.6.4会造成卡死

**Comment by hadix-lin** [comment]
问题收到，尽快解决

**Comment by hadix-lin** [comment]
与#97 问题重复

**Comment by hadix-lin** [comment]
请下载使用1.6.5版本：https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.5/IdeaVimExtension.zip
