### ISSUE TITLE
After upgrading to 1.6.4, the IDE has become very sluggish.

### ISSUE THREAD

**Issue by sunvisor** [hadix-lin/ideavim_extension#97]
After upgrading to 1.6.4, the IDE has become very sluggish.
I disabled this plugin and it recovered. Is there something wrong with this version?

- Mac mini M1 2020
- macOS Monterey 12.5.1

**Comment by yklim** [comment]
I have same issue too.

**Comment by sunvisor** [comment]
As a temporary measure, I am using the following procedure to change the version back to 1.6.3.

1. Download the `IdeaVimExtension.zip` from <https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.3>
2. Remove this plugin from the IDE
3. Select `Install Plugin from Disk...` from the IDE's Preferences > plugin dot menu
4. Specify the zip file you just downloaded

**Comment by hadix-lin** [comment]
#96

**Comment by hadix-lin** [comment]
Please download and install [1.6.5](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.5/IdeaVimExtension.zip)

**Comment by sunvisor** [comment]
THX It works very well.
