### ISSUE TITLE
very slow when install v1.6.4

### ISSUE THREAD

**Issue by zhanggang807** [hadix-lin/ideavim_extension#98]
very slow when install plugin v1.6.4

IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022

Runtime version: 17.0.3+7-b469.37 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    documentation.show.toolbar=true
    ide.allow.merge.buttons=false
    terminal.use.conpty.on.windows=false

**Comment by hadix-lin** [comment]
#97 

please download and install [1.6.5](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.5/IdeaVimExtension.zip)
