### ISSUE TITLE
1.6.4版本导致idea界面卡死

### ISSUE THREAD

**Issue by HeCHieh** [hadix-lin/ideavim_extension#99]
插件版本:1.6.4
idea版本: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
系统: m1 pro macOS
今天升级插件到1.6.4以后重启，打开项目以后界面光标移动变卡，快速切换光标idea直接卡死

**Comment by hadix-lin** [comment]
Duplicated with https://github.com/hadix-lin/ideavim_extension/issues/97

please download and install [1.6.5](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.6.5/IdeaVimExtension.zip)
